package consts

import (
	"pixel-remastered-save-editor/models"
)

var (
	Weapons = []models.NameValue{
		models.NewNameValue("[Empty R. Hand]", 47),
		models.NewNameValue("Knife", 48),
		models.NewNameValue("Dagger", 49),
		models.NewNameValue("Mythril Knife", 50),
		models.NewNameValue("Main Gauche", 51),
		models.NewNameValue("Orichalcum", 52),
		models.NewNameValue("Ripper", 53),
		models.NewNameValue("Cat Claws", 54),
		models.NewNameValue("Staff", 55),
		models.NewNameValue("Mace", 56),
		models.NewNameValue("Mythril Mace", 57),
		models.NewNameValue("Werebuster", 58),
		models.NewNameValue("Mage's Staff", 59),
		models.NewNameValue("Power Staff", 60),
		models.NewNameValue("Wizard's Staff", 61),
		models.NewNameValue("Healing Staff", 62),
		models.NewNameValue("Diamond Mace", 63),
		models.NewNameValue("Javelin", 64),
		models.NewNameValue("Spear", 65),
		models.NewNameValue("Mythril Spear", 66),
		models.NewNameValue("Trident", 67),
		models.NewNameValue("Demon Spear", 68),
		models.NewNameValue("Flame Lance", 69),
		models.NewNameValue("Ice Lance", 70),
		models.NewNameValue("Thunder Spear", 71),
		models.NewNameValue("Holy Lance", 72),
		models.NewNameValue("Broadsword", 73),
		models.NewNameValue("Longsword", 74),
		models.NewNameValue("Mythril Sword", 75),
		models.NewNameValue("Ancient Sword", 76),
		models.NewNameValue("Sleep Blade", 77),
		models.NewNameValue("Wing Sword", 78),
		models.NewNameValue("Blood Sword", 79),
		models.NewNameValue("Gaia Blade", 80),
		models.NewNameValue("Flame Sword", 81),
		models.NewNameValue("Ice Brand", 82),
		models.NewNameValue("Defender", 83),
		models.NewNameValue("Sun Blade", 84),
		models.NewNameValue("Excalibur", 85),
		models.NewNameValue("Masamune", 86),
		models.NewNameValue("Axe", 87),
		models.NewNameValue("Battle Axe", 88),
		models.NewNameValue("Mythril Axe", 89),
		models.NewNameValue("Demon Axe", 90),
		models.NewNameValue("Ogrekiller", 91),
		models.NewNameValue("Poison Axe", 92),
		models.NewNameValue("Rune Axe", 93),
		models.NewNameValue("Bow", 94),
		models.NewNameValue("Longbow", 95),
		models.NewNameValue("Mythril Bow", 96),
		models.NewNameValue("Dark Bow", 97),
		models.NewNameValue("Flame Bow", 98),
		models.NewNameValue("Ice Bow", 99),
		models.NewNameValue("Yoichi Bow", 101),
	}
	Shields = []models.NameValue{
		models.NewNameValue("[Empty L. Hand]", 130),
		models.NewNameValue("Buckler", 102),
		models.NewNameValue("Bronze Shield", 203),
		models.NewNameValue("Mythril Shield", 104),
		models.NewNameValue("Golden Shield", 105),
		models.NewNameValue("Ice Shield", 106),
		models.NewNameValue("Flame Shield", 107),
		models.NewNameValue("Diamond Shield", 108),
		models.NewNameValue("Dragon Shield", 109),
		models.NewNameValue("Aegis Shield", 110),
	}
	Helmets = []models.NameValue{
		models.NewNameValue("[Empty Head]", 210),
		models.NewNameValue("Leather Cap", 111),
		models.NewNameValue("Bronze Helm", 112),
		models.NewNameValue("Mythril Helm", 113),
		models.NewNameValue("Giant's Helm", 114),
		models.NewNameValue("Flame Helm", 115),
		models.NewNameValue("Diamond Helm", 116),
		models.NewNameValue("Genji Helm", 117),
		models.NewNameValue("Twist Headband", 118),
		models.NewNameValue("Gold Hairpin", 119),
		models.NewNameValue("Ribbon", 120),
	}
	Armors = []models.NameValue{
		models.NewNameValue("[Empty Body]", 209),
		models.NewNameValue("Clothes", 121),
		models.NewNameValue("Leather Armor", 122),
		models.NewNameValue("Bronze Armor", 123),
		models.NewNameValue("Mythril Armor", 124),
		models.NewNameValue("Golden Armor", 125),
		models.NewNameValue("Knight's Armor", 126),
		models.NewNameValue("Flame Armor", 127),
		models.NewNameValue("Ice Armor", 128),
		models.NewNameValue("Diamond Armor", 129),
		models.NewNameValue("Dragon Armor", 130),
		models.NewNameValue("Genji Armor", 131),
		models.NewNameValue("Copper Cuirass", 132),
		models.NewNameValue("Silver Cuirass", 133),
		models.NewNameValue("Ruby Cuirass", 134),
		models.NewNameValue("Gold Cuirass", 135),
		models.NewNameValue("Diamond Cuirass", 136),
		models.NewNameValue("White Robe", 137),
		models.NewNameValue("Black Robe", 138),
		models.NewNameValue("Power Sash", 139),
		models.NewNameValue("Black Garb", 140),
	}
	Gloves = []models.NameValue{
		models.NewNameValue("[Empty Arms]", 211),
		models.NewNameValue("Leather Gloves", 141),
		models.NewNameValue("Bronze Gloves", 142),
		models.NewNameValue("Mythril Gloves", 143),
		models.NewNameValue("Thief's Gloves", 144),
		models.NewNameValue("Giant's Gloves", 145),
		models.NewNameValue("Ice Gloves", 146),
		models.NewNameValue("Diamond Gloves", 147),
		models.NewNameValue("Genji Gloves", 148),
		models.NewNameValue("Protect Ring", 149),
		models.NewNameValue("Power Armlet", 150),
	}
)
