package consts

import (
	"pixel-remastered-save-editor/models"
)

var (
	Items = []models.NameValue{
		models.NewNameValue("Potion", 16),
		models.NewNameValue("Antidote", 17),
		models.NewNameValue("Gold Needle", 18),
		models.NewNameValue("Cross", 19),
		models.NewNameValue("Maiden's Kiss", 20),
		models.NewNameValue("Mallet", 21),
		models.NewNameValue("Eye Drops", 22),
		models.NewNameValue("Phoenix Down", 23),
		models.NewNameValue("Elixir", 24),
		models.NewNameValue("Hi-Potion", 26),
		models.NewNameValue("Cottage", 27),
		models.NewNameValue("Wind Flute", 28),
		models.NewNameValue("Gaia Drum", 29),
		models.NewNameValue("Garlic", 30),
		models.NewNameValue("Unicorn Horn", 31),
		models.NewNameValue("Antarctic Wind", 32),
		models.NewNameValue("Sage's Wisdom", 33),
		models.NewNameValue("Saint's Spirit", 34),
		models.NewNameValue("Hermes's Shoes", 35),
		models.NewNameValue("Spider Silk", 36),
		models.NewNameValue("Bell of Silence", 37),
		models.NewNameValue("Hourglass", 38),
		models.NewNameValue("Death Idol", 39),
		models.NewNameValue("Bacchus's Wine", 40),
		models.NewNameValue("Acid Phial", 41),
		models.NewNameValue("Sleepgrass", 42),
		models.NewNameValue("Conch Shell", 43),
		models.NewNameValue("Betrayal Fang", 44),
		models.NewNameValue("Mythril Mirror", 45),
		models.NewNameValue("Hellfire", 46),
		models.NewNameValue("Fire Tome", 151),
		models.NewNameValue("Thunder Tome", 152),
		models.NewNameValue("Blizzard Tome", 153),
		models.NewNameValue("Scourge Tome", 154),
		models.NewNameValue("Drain Tome", 155),
		models.NewNameValue("Osmose Tome", 156),
		models.NewNameValue("Flare Tome", 157),
		models.NewNameValue("Sleep Tome", 158),
		models.NewNameValue("Stun Tome", 159),
		models.NewNameValue("Stop Tome", 160),
		models.NewNameValue("Confuse Tome", 161),
		models.NewNameValue("Blind Tome", 162),
		models.NewNameValue("Curse Tome", 163),
		models.NewNameValue("Toad Tome", 164),
		models.NewNameValue("Break Tome", 165),
		models.NewNameValue("Death Tome", 166),
		models.NewNameValue("Warp Tome", 167),
		models.NewNameValue("Berserk Tome", 168),
		models.NewNameValue("Haste Tome", 169),
		models.NewNameValue("Aura Tome", 170),
		models.NewNameValue("Cure Tome", 171),
		models.NewNameValue("Life Tome", 172),
		models.NewNameValue("Basuna Tome", 173),
		models.NewNameValue("Esuna Tome", 174),
		models.NewNameValue("Barrier Tome", 175),
		models.NewNameValue("Blink Tome", 176),
		models.NewNameValue("Protect Tome", 177),
		models.NewNameValue("Shell Tome", 178),
		models.NewNameValue("Wall Tome", 179),
		models.NewNameValue("Dispel Tome", 180),
		models.NewNameValue("Mini Tome", 181),
		models.NewNameValue("Silence Tome", 182),
		models.NewNameValue("Sap Tome", 183),
		models.NewNameValue("Fog Tome", 184),
		models.NewNameValue("Slow Tome", 185),
		models.NewNameValue("Swap Tome", 186),
		models.NewNameValue("Fear Tome", 187),
		models.NewNameValue("Holy Tome", 188),
		models.NewNameValue("Teleport Tome", 189),
		models.NewNameValue("Ultima Tome", 190),
	}
	ImportantItems = []models.NameValue{
		// models.NewNameValue("Ring",),
		// models.NewNameValue("Canoe",),
		// models.NewNameValue("Pass",),
		// models.NewNameValue("Mythril",),
		// models.NewNameValue("Snowcraft",),
		// models.NewNameValue("Goddess's Bell",),
		// models.NewNameValue("Egil's Torch",),
		// models.NewNameValue("Sunfire",),
		// models.NewNameValue("Pendant",),
		// models.NewNameValue("Wyvern Egg",),
		// models.NewNameValue("White Mask",),
		// models.NewNameValue("Black Mask",),
		// models.NewNameValue("Crystal Rod",),
		// models.NewNameValue("Wyvern",),
	}
)
