package consts

import (
	"pixel-remastered-save-editor/models"
)

var Maps = []models.NameValue{
	models.NewNameValue("World Map", 1),
	models.NewNameValue("Altair", 2),
	models.NewNameValue("Rebel Hideout", 3),
	models.NewNameValue("Altair - Sanctuary", 4),
	models.NewNameValue("Altair - Magic Shop", 5),
	models.NewNameValue("Rebel Hideout - Throne Room", 6),
	models.NewNameValue("Rebel Hideout - Magic Circle Room", 7),
	models.NewNameValue("Rebel Hideout - King's Room", 8),
	models.NewNameValue("Rebel Hideout - Hilda's Room", 9),
	models.NewNameValue("Altair - Inn", 10),
	models.NewNameValue("Altair - Armor Shop", 11),
	models.NewNameValue("Altair - Item Shop", 12),
	models.NewNameValue("Altair - Weapon Shop", 13),
	models.NewNameValue("Gatrea", 14),
	models.NewNameValue("Gatrea - Inn", 15),
	models.NewNameValue("Gatrea - Item Shop", 16),
	models.NewNameValue("Gatrea - Weapon Shop", 17),
	models.NewNameValue("Gatrea - Armor Shop", 18),
	models.NewNameValue("Gatrea - Sanctuary", 19),
	models.NewNameValue("Fynn", 20),
	models.NewNameValue("Fynn - Paul's House", 21),
	models.NewNameValue("Fynn - Paul's Secret Basement", 22),
	models.NewNameValue("Fynn - Armor Shop", 23),
	models.NewNameValue("Fynn - Weapon Shop", 24),
	models.NewNameValue("Fynn - Magic Shop", 25),
	models.NewNameValue("Fynn - Pub", 26),
	models.NewNameValue("Fynn - Pub Secret Basement (Scott's room)", 27),
	models.NewNameValue("Fynn - Inn", 28),
	models.NewNameValue("Fynn - Item Shop", 29),
	models.NewNameValue("Fynn - Sanctuary", 30),
	models.NewNameValue("Castle Fynn 1F", 31),
	models.NewNameValue("Castle Fynn - Secret Passage 2F", 32),
	models.NewNameValue("Castle Fynn - B1", 33),
	models.NewNameValue("Castle Fynn - B2", 34),
	models.NewNameValue("Castle Fynn - B3", 35),
	models.NewNameValue("Castle Fynn - B4", 36),
	models.NewNameValue("Castle Fynn - B5", 37),
	models.NewNameValue("Castle Fynn - 1F Treasure Room", 38),
	models.NewNameValue("Castle Fynn - 2F", 39),
	models.NewNameValue("Castle Fynn - 3F Main Area", 40),
	models.NewNameValue("Castle Fynn - 3F Mirror Room", 41),
	models.NewNameValue("Castle Fynn - 3F Treasure Room", 42),
	models.NewNameValue("Castle Fynn - Throne Room", 43),
	models.NewNameValue("Castle Fynn - Secret Passage 4F", 44),
	models.NewNameValue("Castle Fynn - Secret Passage 3F", 45),
	models.NewNameValue("Paloom", 46),
	models.NewNameValue("Paloom - Item Shop", 47),
	models.NewNameValue("Paloom - Inn", 48),
	models.NewNameValue("Paloom - Weapon Shop", 49),
	models.NewNameValue("Paloom - Armor Shop", 50),
	models.NewNameValue("Paloom - Magic Shop", 51),
	models.NewNameValue("Poft", 52),
	models.NewNameValue("Poft - Pub", 53),
	models.NewNameValue("Poft - Item Shop", 54),
	models.NewNameValue("Poft - Inn", 55),
	models.NewNameValue("Poft - Weapon Shop", 56),
	models.NewNameValue("Poft - Armor Shop", 57),
	models.NewNameValue("Poft - Magic Shop", 58),
	models.NewNameValue("Salamand", 59),
	models.NewNameValue("Salamand - Josef's House", 60),
	models.NewNameValue("Salamand - Inn", 61),
	models.NewNameValue("Salamand - Weapon Shop", 62),
	models.NewNameValue("Salamand - Armor Shop", 63),
	models.NewNameValue("Salamand - Sanctuary", 64),
	models.NewNameValue("Salamand - Magic Shop", 65),
	models.NewNameValue("Salamand - Item Shop", 66),
	models.NewNameValue("Bafsk", 67),
	models.NewNameValue("Bafsk - Item Shop", 68),
	models.NewNameValue("Bafsk - Sanctuary", 69),
	models.NewNameValue("Bafsk - Inn", 70),
	models.NewNameValue("Bafsk - Magic Shop", 71),
	models.NewNameValue("Bafsk - Weapon Shop", 72),
	models.NewNameValue("Bafsk - Armor Shop", 73),
	models.NewNameValue("Rebel Camp", 74),
	models.NewNameValue("Fynn Castle - B5 White Mask Room", 75),
	models.NewNameValue("Fynn Castle - Trap Room", 76),
	models.NewNameValue("Fynn Castle - Trap Room", 77),
	models.NewNameValue("Fynn Castle - Trap Room", 78),
	models.NewNameValue("Fynn Castle - Trap Room", 79),
	models.NewNameValue("Fynn Castle - Trap Room", 80),
	models.NewNameValue("Fynn Castle - Trap Room", 81),
	models.NewNameValue("Fynn Castle - Trap Room", 82),
	models.NewNameValue("Fynn Castle - Trap Room", 83),
	models.NewNameValue("Fynn Castle - Trap Room", 84),
	models.NewNameValue("Fynn Castle - Trap Room", 85),
	models.NewNameValue("Fynn Castle - Trap Room", 86),
	models.NewNameValue("Fynn Castle - Trap Room", 87),
	models.NewNameValue("Fynn Castle - Trap Room", 88),
	models.NewNameValue("Castle Fynn - Throne Room", 89),
	models.NewNameValue("Mysidia", 90),
	models.NewNameValue("Mysidia - Weapon Shop", 91),
	models.NewNameValue("Mysidia - Inn", 92),
	models.NewNameValue("Mysidia - Item Shop", 93),
	models.NewNameValue("Mysidia - Armor Shop", 94),
	models.NewNameValue("Mysidia - Magic Shop", 95),
	models.NewNameValue("Mysidia - Sanctuary", 96),
	models.NewNameValue("Mysidia - House with Bookshelf", 97),
	models.NewNameValue("Mysidia - Goddess Statue Area", 98),
	models.NewNameValue("Chocobo Forest", 99),
	models.NewNameValue("Leila's Ship", 100),
	models.NewNameValue("Altair (Post-Dreadnought)", 101),
	models.NewNameValue("Altair - Inn (Post-Dreadnought)", 102),
	models.NewNameValue("Altair - Armor Shop (Post-Dreadnought)", 103),
	models.NewNameValue("Altair - Weapon Shop (Post-Dreadnought)", 104),
	models.NewNameValue("Altair - Item Shop (Post-Dreadnought)", 105),
	models.NewNameValue("Altair - Magic Shop (Post-Dreadnought)", 106),
	models.NewNameValue("Gatrea (Post-Dreadnought)", 107),
	models.NewNameValue("Gatrea - Inn (Post-Dreadnought)", 108),
	models.NewNameValue("Gatrea - Item Shop (Post-Dreadnought)", 109),
	models.NewNameValue("Gatrea - Weapon Shop (Post-Dreadnought)", 110),
	models.NewNameValue("Gatrea - Armor Shop (Post-Dreadnought)", 111),
	models.NewNameValue("Paloom (Post-Dreadnought)", 112),
	models.NewNameValue("Paloom - Inn (Post-Dreadnought)", 113),
	models.NewNameValue("Paloom - Weapon Shop (Post-Dreadnought)", 114),
	models.NewNameValue("Poft (Post-Dreadnought)", 115),
	models.NewNameValue("Poft - Pub (Post-Dreadnought)", 116),
	models.NewNameValue("Poft - Inn (Post-Dreadnought)", 117),
	models.NewNameValue("Semitt Falls - B1", 118),
	models.NewNameValue("Semitt Falls - B2", 128),
	models.NewNameValue("Semitt Falls - B3", 131),
	models.NewNameValue("Semitt Falls - B4", 133),
	models.NewNameValue("Semitt Falls - B5", 134),
	models.NewNameValue("Bafsk Cave - B1", 136),
	models.NewNameValue("Bafsk Cave - B2", 137),
	models.NewNameValue("Snow Cavern - B1", 139),
	models.NewNameValue("Snow Cavern - B2", 141),
	models.NewNameValue("Snow Cavern - B3", 143),
	models.NewNameValue("Snow Cavern - B4", 144),
	models.NewNameValue("Snow Cavern - B5", 145),
	models.NewNameValue("Snow Cavern - B6", 146),
	models.NewNameValue("Snow Cavern - B6", 147),
	models.NewNameValue("Kashuan Keep - 1F", 149),
	models.NewNameValue("Kashuan Keep 1F", 156),
	models.NewNameValue("Kashuan Keep 2F", 158),
	models.NewNameValue("Kashuan Keep 3F", 159),
	models.NewNameValue("Kashuan Keep 4F", 160),
	models.NewNameValue("Kashuan Keep 5F", 162),
	models.NewNameValue("Deist Cavern B1", 183),
	models.NewNameValue("Deist Cavern B2", 184),
	models.NewNameValue("Deist Cavern B3", 185),
	models.NewNameValue("Deist Cavern B4", 186),
	models.NewNameValue("Deist Cavern B5", 187),
	models.NewNameValue("Coliseum 1F", 191),
	models.NewNameValue("Coliseum B2", 192),
	models.NewNameValue("Coliseum B1", 195),
	models.NewNameValue("Tropical Island B1", 200),
	models.NewNameValue("Tropical Island B2", 201),
	models.NewNameValue("Tropical Island B3", 202),
	models.NewNameValue("Tropical Island B4", 203),
	models.NewNameValue("Tropical Island B5", 204),
	models.NewNameValue("Cave of Mysidia B1", 207),
	models.NewNameValue("Cave of Mysidia B5", 208),
	models.NewNameValue("Cave of Mysidia B2", 221),
	models.NewNameValue("Cave of Mysidia B3", 223),
	models.NewNameValue("Cave of Mysidia B4", 225),
	models.NewNameValue("Mysidian Tower 1F", 231),
	models.NewNameValue("Mysidian Tower 6F", 232),
	models.NewNameValue("Mysidian Tower 7F", 234),
	models.NewNameValue("Mysidian Tower 8F", 236),
	models.NewNameValue("Mysidian Tower 9F", 238),
	models.NewNameValue("Mysidian Tower 10F", 240),
	models.NewNameValue("Mysidian Tower 2F", 242),
	models.NewNameValue("Mysidian Tower 3F", 253),
	models.NewNameValue("Mysidian Tower 4F", 262),
	models.NewNameValue("Mysidian Tower 5F", 263),
	models.NewNameValue("Cyclone 1F", 265),
	models.NewNameValue("Cyclone 2F", 268),
	models.NewNameValue("Cyclone 3F", 269),
	models.NewNameValue("Cyclone 4F", 270),
	models.NewNameValue("Cyclone 5F", 271),
	models.NewNameValue("Cyclone 6F", 272),
	models.NewNameValue("Castle Palamecia 7F", 276),
	models.NewNameValue("Castle Palamecia 6F", 277),
	models.NewNameValue("Castle Palamecia 8F", 278),
	models.NewNameValue("Castle Palamecia 1F", 282),
	models.NewNameValue("Castle Palamecia 2F", 283),
	models.NewNameValue("Castle Palamecia 3F", 284),
	models.NewNameValue("Castle Palamecia 4F", 285),
	models.NewNameValue("Castle Palamecia 5F", 287),
	models.NewNameValue("Jade Passage B5", 290),
	models.NewNameValue("Jade Passage B6", 292),
	models.NewNameValue("Jade Passage B1", 299),
	models.NewNameValue("Jade Passage B2", 308),
	models.NewNameValue("Jade Passage B3", 310),
	models.NewNameValue("Jade Passage B4", 312),
	models.NewNameValue("Paloom item shop", 332),
	models.NewNameValue("Paloom armor shop", 333),
	models.NewNameValue("Paloom magic shop", 334),
	models.NewNameValue("Poft item shop", 335),
	models.NewNameValue("Poft weapon shop", 336),
	models.NewNameValue("Poft armor shop", 337),
	models.NewNameValue("Poft magic shop", 338),
	models.NewNameValue("Altair", 355),
}
