package consts

import (
	"pixel-remastered-save-editor/models"
)

var (
	Weapons = []models.NameValue{
		models.NewNameValue("Empty", 102),
		models.NewNameValue("Knife", 104),
		models.NewNameValue("Dagger", 108),
		models.NewNameValue("Mythril Knife", 115),
		models.NewNameValue("Main Gauche", 127),
		models.NewNameValue("Orichalcum", 132),
		models.NewNameValue("Ripper", 141),
		models.NewNameValue("Cat Claws", 148),
		models.NewNameValue("Staff", 105),
		models.NewNameValue("Mace", 110),
		models.NewNameValue("Mythril Mace", 117),
		models.NewNameValue("Werebuster", 124),
		models.NewNameValue("Mage's Staff", 128),
		models.NewNameValue("Power Staff", 134),
		models.NewNameValue("Wizard's Staff", 139),
		models.NewNameValue("Healing Staff", 146),
		models.NewNameValue("Diamond Mace", 150),
		models.NewNameValue("Javelin", 107),
		models.NewNameValue("Spear", 112),
		models.NewNameValue("Mythril Spear", 118),
		models.NewNameValue("Trident", 126),
		models.NewNameValue("Demon Spear", 131),
		models.NewNameValue("Flame Lance", 135),
		models.NewNameValue("Ice Lance", 140),
		models.NewNameValue("Thunder Spear", 145),
		models.NewNameValue("Holy Lance", 149),
		models.NewNameValue("Broadsword", 109),
		models.NewNameValue("Longsword", 114),
		models.NewNameValue("Mythril Sword", 119),
		models.NewNameValue("Ancient Sword", 122),
		models.NewNameValue("Sleep Blade", 125),
		models.NewNameValue("Wing Sword", 130),
		models.NewNameValue("Blood Sword", 101),
		models.NewNameValue("Gaia Blade", 133),
		models.NewNameValue("Flame Sword", 138),
		models.NewNameValue("Ice Brand", 142),
		models.NewNameValue("Defender", 144),
		models.NewNameValue("Sun Blade", 147),
		models.NewNameValue("Excalibur", 153),
		models.NewNameValue("Masamune", 154),
		models.NewNameValue("Axe", 111),
		models.NewNameValue("Battle Axe", 116),
		models.NewNameValue("Mythril Axe", 120),
		models.NewNameValue("Demon Axe", 123),
		models.NewNameValue("Ogrekiller", 137),
		models.NewNameValue("Poison Axe", 143),
		models.NewNameValue("Rune Axe", 152),
		models.NewNameValue("Bow", 103),
		models.NewNameValue("Longbow", 106),
		models.NewNameValue("Mythril Bow", 113),
		models.NewNameValue("Dark Bow", 121),
		models.NewNameValue("Flame Bow", 129),
		models.NewNameValue("Ice Bow", 136),
		models.NewNameValue("Yoichi Bow", 151),
	}
)
