package consts

import (
	"pixel-remastered-save-editor/models"
)

var (
	Commands = []models.NameValue{
		models.NewValueName(1, "Attack"),
		models.NewValueName(2, "Defend"),
		models.NewValueName(3, "Items"),
		models.NewValueName(5, "Row"),
		models.NewValueName(6, "Skip"),
		models.NewValueName(7, "Guard"),
		models.NewValueName(8, "Kick"),
		models.NewValueName(9, "Focus"),
		models.NewValueName(10, "Chakra"),
		models.NewValueName(11, "Scram"),
		models.NewValueName(12, "Steal"),
		models.NewValueName(13, "Mug"),
		models.NewValueName(14, "Jump"),
		models.NewValueName(15, "Lance"),
		models.NewValueName(16, "Smoke"),
		models.NewValueName(17, "Image"),
		models.NewValueName(18, "Throw"),
		models.NewValueName(19, "Mineuchi"),
		models.NewValueName(20, "Zeninage"),
		models.NewValueName(21, "Iainuki"),
		models.NewValueName(22, "Animals"),
		models.NewValueName(23, "Aim"),
		models.NewValueName(24, "Rapid Fire"),
		models.NewValueName(25, "Call"),
		models.NewValueName(26, "Check"),
		models.NewValueName(27, "Scan"),
		models.NewValueName(28, "Calm"),
		models.NewValueName(29, "Control"),
		models.NewValueName(30, "Catch"),
		models.NewValueName(31, "Release"),
		models.NewValueName(32, "Mix"),
		models.NewValueName(33, "Drink"),
		models.NewValueName(34, "Recover"),
		models.NewValueName(35, "Revive"),
		models.NewValueName(36, "Gaia"),
		models.NewValueName(38, "Hide"),
		models.NewValueName(39, "Reveal"),
		models.NewValueName(41, "Sing"),
		models.NewValueName(42, "Flirt"),
		models.NewValueName(43, "Dance"),
		models.NewValueName(44, "Mimic"),
		models.NewValueName(51, "Equip Shields"),
		models.NewValueName(52, "Equip Armor"),
		models.NewValueName(53, "Equip Ribbons"),
		models.NewValueName(54, "Equip Swords"),
		models.NewValueName(55, "Equip Lances"),
		models.NewValueName(56, "Equip Katanas"),
		models.NewValueName(57, "Equip Axes"),
		models.NewValueName(58, "Equip Bows"),
		models.NewValueName(59, "Equip Whips"),
		models.NewValueName(60, "Equip Harps"),
		models.NewValueName(61, "Artful Dodger"),
		models.NewValueName(67, "Barehanded"),
		models.NewValueName(68, "Two-Handed"),
		models.NewValueName(69, "Dual-Wield"),
		models.NewValueName(70, "Pharmacology"),
		models.NewValueName(71, "Cover"),
		models.NewValueName(72, "Counter"),
		models.NewValueName(73, "Shirahadori"),
		models.NewValueName(74, "Learn"),
		models.NewValueName(75, "Magic Shell"),
		models.NewValueName(76, "Berserk"),
		models.NewValueName(77, "Vigilance"),
		models.NewValueName(78, "First Strike"),
		models.NewValueName(79, "Find Passages"),
		models.NewValueName(80, "Light Step"),
		models.NewValueName(81, "Find Pits"),
		models.NewValueName(82, "Equip Rods"),
		models.NewValueName(83, "Sprint"),
	}
)
