package consts

import (
	"pixel-remastered-save-editor/models"
)

var (
	Shields = []models.NameValue{
		models.NewValueName(178, "Leather Shield"),
		models.NewValueName(179, "Bronze Shield"),
		models.NewValueName(180, "Iron Shield"),
		models.NewValueName(181, "Mythril Shield"),
		models.NewValueName(182, "Golden Shield"),
		models.NewValueName(183, "Aegis Shield"),
		models.NewValueName(184, "Diamond Shield"),
		models.NewValueName(185, "Flame Shield"),
		models.NewValueName(186, "Ice Shield"),
		models.NewValueName(187, "Crystal Shield"),
		models.NewValueName(188, "Genji Shield"),
	}
	Armors = []models.NameValue{
		models.NewValueName(175, "[Empty Body]"),
		models.NewValueName(213, "Leather Armor"),
		models.NewValueName(214, "Angel Robe"),
		models.NewValueName(215, "Mirage Vest"),
		models.NewValueName(216, "Rainbow Dress"),
		models.NewValueName(217, "Copper Cuirass"),
		models.NewValueName(218, "Kenpo Gi"),
		models.NewValueName(219, "Silver Plate"),
		models.NewValueName(221, "Ninja Suit"),
		models.NewValueName(222, "Power Sash"),
		models.NewValueName(223, "Diamond Plate"),
		models.NewValueName(224, "Black Garb"),
		models.NewValueName(225, "Bone Mail"),
		models.NewValueName(226, "Cotton Robe"),
		models.NewValueName(227, "Silk Robe"),
		models.NewValueName(228, "Sage's Surplice"),
		models.NewValueName(229, "Gaia Gear"),
		models.NewValueName(230, "Luminous Robe"),
		models.NewValueName(231, "Black Robe"),
		models.NewValueName(232, "White Robe"),
		models.NewValueName(233, "Bronze Armor"),
		models.NewValueName(234, "Iron Armor"),
		models.NewValueName(235, "Mythril Armor"),
		models.NewValueName(236, "Golden Armor"),
		models.NewValueName(237, "Diamond Armor"),
		models.NewValueName(238, "Crystal Armor"),
		models.NewValueName(239, "Genji Armor"),
	}
	Helmets = []models.NameValue{
		models.NewValueName(176, "[Empty Head]"),
		models.NewValueName(190, "Leather Cap"),
		models.NewValueName(191, "Plumed Hat"),
		models.NewValueName(192, "Hypno Crown"),
		models.NewValueName(193, "Green Beret"),
		models.NewValueName(195, "Headband"),
		models.NewValueName(196, "Tiger Mask"),
		models.NewValueName(197, "Black Cowl"),
		models.NewValueName(198, "Lamia's Tiara"),
		models.NewValueName(199, "Wizard's Hat"),
		models.NewValueName(200, "Sage's Miter"),
		models.NewValueName(201, "Circlet"),
		models.NewValueName(202, "Gold Hairpin"),
		models.NewValueName(203, "Ribbon"),
		models.NewValueName(204, "Bronze Helm"),
		models.NewValueName(205, "Iron Helm"),
		models.NewValueName(206, "Mythril Helm"),
		models.NewValueName(207, "Golden Helm"),
		models.NewValueName(208, "Diamond Helm"),
		models.NewValueName(209, "Crystal Helm"),
		models.NewValueName(210, "Genji Helm"),
		models.NewValueName(211, "Thornlet"),
	}
	Hands = []models.NameValue{
		models.NewValueName(177, "[Empty Arms]"),
		models.NewValueName(242, "Mythril Gloves"),
		models.NewValueName(243, "Thief's Gloves"),
		models.NewValueName(244, "Gauntlets"),
		models.NewValueName(245, "Titan's Gloves"),
		models.NewValueName(246, "Genji Gloves"),
		models.NewValueName(247, "Silver Armlet"),
		models.NewValueName(248, "Power Armlet"),
		models.NewValueName(249, "Diamond Armlet"),
		models.NewValueName(250, "Leather Shoes"),
		models.NewValueName(251, "Hermes' Sandals"),
		models.NewValueName(252, "Red Slippers"),
		models.NewValueName(253, "Angel Ring"),
		models.NewValueName(254, "Flame Ring"),
		models.NewValueName(255, "Coral Ring"),
		models.NewValueName(256, "Reflect Ring"),
		models.NewValueName(257, "Protect Ring"),
		models.NewValueName(258, "Cursed Ring"),
		models.NewValueName(259, "Kaiser Knuckles"),
		models.NewValueName(260, "Silver Specs"),
		models.NewValueName(261, "Elven Mantle"),
		models.NewValueName(262, "Kornago Gourd"),
	}
)
