package consts

import (
	"pixel-remastered-save-editor/models"
)

var (
	Weapons = []models.NameValue{
		models.NewValueName(59, "[Empty Hand]"),
		models.NewValueName(60, "Knife"),
		models.NewValueName(61, "Dagger"),
		models.NewValueName(62, "Mythril Knife"),
		models.NewValueName(63, "Mage Masher"),
		models.NewValueName(64, "Main Gauche"),
		models.NewValueName(65, "Orichalcum Dirk"),
		models.NewValueName(66, "Dancing Dagger"),
		models.NewValueName(67, "Air Knife"),
		models.NewValueName(68, "Thief Knife"),
		models.NewValueName(69, "Assassin's Dagger"),
		models.NewValueName(70, "Man-Eater"),
		models.NewValueName(72, "Chicken Knife"),
		models.NewValueName(73, "Kunai"),
		models.NewValueName(74, "Kodachi"),
		models.NewValueName(75, "Sasuke's Katana"),
		models.NewValueName(77, "Broadsword"),
		models.NewValueName(78, "Long Sword"),
		models.NewValueName(79, "Mythril Sword"),
		models.NewValueName(80, "Coral Sword"),
		models.NewValueName(81, "Ancient Sword"),
		models.NewValueName(82, "Sleep Blade"),
		models.NewValueName(83, "Rune Blade"),
		models.NewValueName(84, "Great Sword"),
		models.NewValueName(85, "Excalipoor"),
		models.NewValueName(86, "Enhancer"),
		models.NewValueName(88, "Flametongue"),
		models.NewValueName(89, "Icebrand"),
		models.NewValueName(90, "Blood Sword"),
		models.NewValueName(91, "Defender"),
		models.NewValueName(92, "Excalibur"),
		models.NewValueName(93, "Ragnarok"),
		models.NewValueName(95, "Brave Blade"),
		models.NewValueName(96, "Spear"),
		models.NewValueName(97, "Mythril Spear"),
		models.NewValueName(98, "Trident"),
		models.NewValueName(99, "Wind Spear"),
		models.NewValueName(100, "Heavy Lance"),
		models.NewValueName(101, "Javelin"),
		models.NewValueName(102, "Twin Lance"),
		models.NewValueName(103, "Partisan"),
		models.NewValueName(104, "Holy Lance"),
		models.NewValueName(105, "Dragon Lance"),
		models.NewValueName(106, "Battle Axe"),
		models.NewValueName(107, "Mythril Hammer"),
		models.NewValueName(108, "Ogre Killer"),
		models.NewValueName(110, "War Hammer"),
		models.NewValueName(111, "Death Sickle"),
		models.NewValueName(112, "Poison Axe"),
		models.NewValueName(113, "Gaia Hammer"),
		models.NewValueName(114, "Rune Axe"),
		models.NewValueName(115, "Thor's Hammer"),
		models.NewValueName(116, "Titan's Axe"),
		models.NewValueName(118, "Ashura"),
		models.NewValueName(119, "Wind Slash"),
		models.NewValueName(120, "Osafune"),
		models.NewValueName(121, "Kotetsu"),
		models.NewValueName(122, "Kikuichimonji"),
		models.NewValueName(123, "Murasame"),
		models.NewValueName(124, "Masamune"),
		models.NewValueName(125, "Murakumo"),
		models.NewValueName(127, "Rod"),
		models.NewValueName(128, "Flame Rod"),
		models.NewValueName(129, "Frost Rod"),
		models.NewValueName(130, "Thunder Rod"),
		models.NewValueName(131, "Poison Rod"),
		models.NewValueName(132, "Lilith Rod"),
		models.NewValueName(133, "Magus Rod"),
		models.NewValueName(134, "Wonder Wand"),
		models.NewValueName(136, "Staff"),
		models.NewValueName(137, "Healing Staff"),
		models.NewValueName(138, "Power Staff"),
		models.NewValueName(139, "Staff of Light"),
		models.NewValueName(140, "Sage's Staff"),
		models.NewValueName(141, "Judgment Staff"),
		models.NewValueName(143, "Flail"),
		models.NewValueName(144, "Morning Star"),
		models.NewValueName(145, "Silver Bow"),
		models.NewValueName(146, "Flame Bow"),
		models.NewValueName(147, "Frost Bow"),
		models.NewValueName(148, "Thunder Bow"),
		models.NewValueName(149, "Dark Bow"),
		models.NewValueName(150, "Magic Bow"),
		models.NewValueName(151, "Killer Bow"),
		models.NewValueName(152, "Elven Bow"),
		models.NewValueName(153, "Hayate Bow"),
		models.NewValueName(154, "Aevis Killer"),
		models.NewValueName(155, "Yoichi's Bow"),
		models.NewValueName(156, "Artemis's Bow"),
		models.NewValueName(158, "Silver Harp"),
		models.NewValueName(159, "Dream Harp"),
		models.NewValueName(160, "Lamia's Harp"),
		models.NewValueName(161, "Apollo's Harp"),
		models.NewValueName(162, "Whip"),
		models.NewValueName(163, "Blitz Whip"),
		models.NewValueName(164, "Chain Whip"),
		models.NewValueName(165, "Beast Killer"),
		models.NewValueName(166, "Fire Lash"),
		models.NewValueName(167, "Dragon's Whisker"),
		models.NewValueName(168, "Diamond Bell"),
		models.NewValueName(169, "Gaia Bell"),
		models.NewValueName(170, "Rune Chime"),
		models.NewValueName(171, "Tinklebell"),
		models.NewValueName(172, "Moonring Blade"),
		models.NewValueName(173, "Rising Sun"),
		models.NewValueName(174, "Shuriken"),
		models.NewValueName(175, "Fuma Shuriken"),
	}
)
