package consts

import (
	"pixel-remastered-save-editor/models"
)

var (
	WhiteMagic = []models.NameValue{
		models.NewValueName(9, "Aero"),
		models.NewValueName(21, "Aeroga"),
		models.NewValueName(28, "Arise"),
		models.NewValueName(14, "Blindna"),
		models.NewValueName(16, "Confuse"),
		models.NewValueName(6, "Cure"),
		models.NewValueName(12, "Cura"),
		models.NewValueName(18, "Curaga"),
		models.NewValueName(24, "Curaja"),
		models.NewValueName(25, "Esuna"),
		models.NewValueName(23, "Haste"),
		models.NewValueName(29, "Holy"),
		models.NewValueName(15, "Libra"),
		models.NewValueName(11, "Mini"),
		models.NewValueName(7, "Poisona"),
		models.NewValueName(20, "Protect"),
		models.NewValueName(19, "Raise"),
		models.NewValueName(26, "Reflect"),
		models.NewValueName(8, "Sight"),
		models.NewValueName(17, "Silence"),
		models.NewValueName(22, "Stona"),
		models.NewValueName(13, "Teleport"),
		models.NewValueName(10, "Toad"),
		models.NewValueName(27, "Tornado"),
	}
	BlackMagic = []models.NameValue{
		models.NewValueName(46, "Bio"),
		models.NewValueName(35, "Blind"),
		models.NewValueName(31, "Blizzard"),
		models.NewValueName(37, "Blizzara"),
		models.NewValueName(40, "Blizzaga"),
		models.NewValueName(39, "Break"),
		models.NewValueName(49, "Breakga"),
		models.NewValueName(50, "Drain"),
		models.NewValueName(52, "Death"),
		models.NewValueName(44, "Erase"),
		models.NewValueName(30, "Fire"),
		models.NewValueName(36, "Fira"),
		models.NewValueName(45, "Firaga"),
		models.NewValueName(51, "Flare"),
		models.NewValueName(53, "Meteor"),
		models.NewValueName(34, "Poison"),
		models.NewValueName(48, "Quake"),
		models.NewValueName(43, "Raze"),
		models.NewValueName(41, "Shade"),
		models.NewValueName(32, "Sleep"),
		models.NewValueName(33, "Thunder"),
		models.NewValueName(38, "Thundara"),
		models.NewValueName(42, "Thundaga"),
		models.NewValueName(47, "Warp"),
	}
	SummonMagic = []models.NameValue{
		models.NewValueName(61, "Bahamur"),
		models.NewValueName(59, "Catastro"),
		models.NewValueName(54, "Escape"),
		models.NewValueName(57, "Heatra"),
		models.NewValueName(58, "Hyper"),
		models.NewValueName(55, "Icen"),
		models.NewValueName(60, "Leviath"),
		models.NewValueName(56, "Spark"),
	}
	Songs = []models.NameValue{
		models.NewValueName(110, "Paeon"),
		models.NewValueName(108, "Minuet"),
		models.NewValueName(109, "Elegy"),
		models.NewValueName(111, "Requiem"),
	}
)

/*
{ID:62,Name:"Barrier Shift"),
{ID:63,Name:"Barrier Shift"),
{ID:64,Name:"Barrier Shift"),
{ID:65,Name:"Bad Breath"),
{ID:66,Name:"Self-Destruct"),
{ID:67,Name:"Flame"),
{ID:68,Name:"Lightning"),
{ID:69,Name:"Lightning"),
{ID:70,Name:"Multiply"),
{ID:71,Name:"Multiply"),
{ID:72,Name:"Multiply"),
{ID:73,Name:"Multiply"),
{ID:74,Name:"Earthquake"),
{ID:75,Name:"Snowstorm"),
{ID:76,Name:"Summon"),
{ID:77,Name:"Summon"),
{ID:78,Name:"Zantetsuken"),
{ID:79,Name:"Tsunami"),
{ID:80,Name:"Mega Flare"),
{ID:81,Name:"Mega Flare"),
{ID:82,Name:"Stare"),
{ID:83,Name:"Stare"),
{ID:84,Name:"Stare"),

{ID:91,Name:"Jump, landing version?"),

{ID:97,Name:"Kick"),
{ID:98,Name:"Terrain ability?"),
{ID:99"),
{ID:100,Name:"Terrain ability?"),
{ID:101,Name:"Terrain ability?"),
{ID:102"),
{ID:103,Name:"Terrain ability?"),
{ID:104,Name:"Terrain ability?"),
{ID:105,Name:"Terrain ability?"),

{ID:112,Name:"Chocobo Dash"),
{ID:113,Name:"Chocobo Kick?"),
{ID:114,Name:"Chocobo Kick"),
{ID:115,Name:"Mesmerize"),
{ID:116,Name:"Icy Stare"),
{ID:117,Name:"Diamond Dust"),
{ID:118,Name:"Mind Blast"),
{ID:119,Name:"Thunderstorm"),
{ID:120,Name:"Judgment Bolt"),
{ID:121,Name:"Healing Light"),
{ID:122,Name:"Hellfire"),
{ID:123,Name:"Inferno"),
{ID:124,Name:"Clobber"),
{ID:125,Name:"Stomp"),
{ID:126,Name:"Earthen Fury"),
{ID:127,Name:"Protective Light"),
{ID:128,Name:"Slash"),
{ID:129,Name:"Zantetsuken"),
{ID:130,Name:"Demon Eye"),
{ID:131,Name:"Cyclone"),
{ID:132,Name:"Tidal Wave"),
{ID:133,Name:"Aura"),
{ID:134"),
{ID:135,Name:"Mega Flare"),
{ID:136"),
{ID:137,Name:"Boost effect?"),
{ID:138"),
{ID:139,Name:"Boost effect?"),
{ID:140"),
{ID:141,Name:"The artillery is providing cover!"),
{ID:142,Name:"142-165 are Attack abilities for various enemies - inflict different statuses"),
{ID:143"),
{ID:144"),
{ID:145"),
{ID:146"),
{ID:147"),
{ID:148"),
{ID:149"),
{ID:150"),
{ID:151"),
{ID:152"),
{ID:153"),
{ID:154"),
{ID:155,Name:"Attack (enemy version, inflicts Poison)"),
{ID:156"),
{ID:157"),
{ID:158"),
{ID:159"),
{ID:160"),
{ID:161"),
{ID:162"),
{ID:163"),
{ID:164"),
{ID:165"),
{ID:166,Name:"166-171 are Divide abilities for various enemies"),
{ID:167"),
{ID:168"),
{ID:169"),
{ID:170"),
{ID:171"),
{ID:172,Name:"<IC_WMGC>Cure"),
{ID:173,Name:"<IC_WMGC>Protect"),
{ID:174,Name:"<IC_WMGC>Haste"),
{ID:175,Name:"<IC_WMGC>Curaja"),
{ID:176,Name:"<IC_WMGC>Reflect"),
{ID:177,Name:"<IC_BMGC>Fira"),
{ID:178,Name:"<IC_WMGC>Mini"),
{ID:180,Name:"Lightning"),
{ID:181,Name:"Rend"),
{ID:182,Name:"Rend"),
{ID:183,Name:"Flame"),
{ID:184,Name:"<IC_WMGC>Cure"),
{ID:185,Name:"<IC_WMGC>Aero"),
{ID:186,Name:"<IC_WMGC>Holy"),
{ID:187,Name:"<IC_BMGC>Fire"),
{ID:188,Name:"<IC_BMGC>Blizzard"),
{ID:189,Name:"<IC_BMGC>Thunder"),
{ID:190,Name:"<IC_BMGC>Thundara"),
{ID:191,Name:"<IC_BMGC>Break"),
{ID:192,Name:"<IC_BMGC>Blizzaga"),
{ID:193,Name:"<IC_WMGC>Aero"),
{ID:194,Name:"<IC_WMGC>Aeroga"),
{ID:195,Name:"<IC_WMGC>Holy"),
{ID:196,Name:"<IC_BMGC>Fire"),
{ID:197,Name:"<IC_BMGC>Blizzard"),
{ID:198,Name:"<IC_BMGC>Thunder"),
{ID:199,Name:"<IC_BMGC>Poison"),
{ID:200,Name:"<IC_BMGC>Fira"),
{ID:201,Name:"<IC_BMGC>Blizzara"),
{ID:202,Name:"<IC_BMGC>Thundara"),
{ID:203,Name:"<IC_BMGC>Break"),
{ID:204,Name:"<IC_BMGC>Blizzaga"),
{ID:205,Name:"<IC_BMGC>Thundaga"),
{ID:206,Name:"<IC_BMGC>Firaga"),
{ID:207,Name:"<IC_BMGC>Quake"),
{ID:208,Name:"<IC_BMGC>Quake"),
{ID:209,Name:"<IC_BMGC>Drain"),
{ID:210,Name:"<IC_BMGC>Flare"),
{ID:211,Name:"<IC_BMGC>Meteor"),
{ID:212,Name:"Particle Beam
*/
