package consts

import (
	"pixel-remastered-save-editor/models"
)

var (
	Items = []models.NameValue{
		models.NewValueName(2, "Potion"),
		models.NewValueName(3, "Hi-Potion"),
		models.NewValueName(4, "Antidote"),
		models.NewValueName(5, "Eye Drops"),
		models.NewValueName(6, "Echo Herbs"),
		models.NewValueName(7, "Gold Needle"),
		models.NewValueName(8, "Maiden's Kiss"),
		models.NewValueName(9, "Mallet"),
		models.NewValueName(10, "Ottershroom"),
		models.NewValueName(11, "Phoenix Down"),
		models.NewValueName(12, "Elixir"),
		models.NewValueName(13, "Gnomish Bread"),
		models.NewValueName(14, "Magic Key"),
		models.NewValueName(15, "Gysahl Greens"),
		models.NewValueName(16, "Antarctic Wind"),
		models.NewValueName(17, "Zeus's Wrath"),
		models.NewValueName(18, "Bomb Fragment"),
		models.NewValueName(19, "Lamia Scale"),
		models.NewValueName(20, "Bacchus's Cider"),
		models.NewValueName(21, "Tranquilizer"),
		models.NewValueName(22, "Bomb Arm"),
		models.NewValueName(23, "Arctic Wind"),
		models.NewValueName(24, "Heavenly Wrath"),
		models.NewValueName(25, "Earthen Drum"),
		models.NewValueName(26, "Turtle Shell"),
		models.NewValueName(27, "Demon's Sigh"),
		models.NewValueName(28, "Black Hole"),
		models.NewValueName(29, "Black Musk"),
		models.NewValueName(30, "Lilith's Kiss"),
		models.NewValueName(31, "Raven's Yawn"),
		models.NewValueName(32, "Shell Breaker"),
		models.NewValueName(33, "Silence Seal"),
		models.NewValueName(34, "Sheep Pillow"),
		models.NewValueName(35, "Shining Curtain"),
		models.NewValueName(36, "Chocobo's Wrath"),
		models.NewValueName(37, "White Musk"),
		models.NewValueName(278, "Cure"),
		models.NewValueName(279, "Poisona"),
		models.NewValueName(280, "Sight"),
		models.NewValueName(281, "Aero"),
		models.NewValueName(282, "Toad"),
		models.NewValueName(283, "Mini"),
		models.NewValueName(284, "Cura"),
		models.NewValueName(285, "Teleport"),
		models.NewValueName(286, "Blindna"),
		models.NewValueName(287, "Libra"),
		models.NewValueName(288, "Confuse"),
		models.NewValueName(289, "Silence"),
		models.NewValueName(290, "Curaga"),
		models.NewValueName(291, "Raise"),
		models.NewValueName(292, "Protect"),
		models.NewValueName(293, "Aeroga"),
		models.NewValueName(294, "Stona"),
		models.NewValueName(295, "Haste"),
		models.NewValueName(296, "Curaja"),
		models.NewValueName(297, "Esuna"),
		models.NewValueName(298, "Reflect"),
		models.NewValueName(299, "Tornado"),
		models.NewValueName(300, "Arise"),
		models.NewValueName(301, "Holy"),
		models.NewValueName(302, "Fire"),
		models.NewValueName(303, "Blizzard"),
		models.NewValueName(304, "Sleep"),
		models.NewValueName(305, "Thunder"),
		models.NewValueName(306, "Poison"),
		models.NewValueName(307, "Blind"),
		models.NewValueName(308, "Fira"),
		models.NewValueName(309, "Blizzara"),
		models.NewValueName(310, "Thundara"),
		models.NewValueName(311, "Break"),
		models.NewValueName(312, "Blizzaga"),
		models.NewValueName(313, "Shade"),
		models.NewValueName(314, "Thundaga"),
		models.NewValueName(315, "Raze"),
		models.NewValueName(316, "Erase"),
		models.NewValueName(317, "Firaga"),
		models.NewValueName(318, "Bio"),
		models.NewValueName(319, "Warp"),
		models.NewValueName(320, "Quake"),
		models.NewValueName(321, "Breakga"),
		models.NewValueName(322, "Drain"),
		models.NewValueName(323, "Flare"),
		models.NewValueName(324, "Death"),
		models.NewValueName(325, "Meteor"),
		models.NewValueName(326, "Escape"),
		models.NewValueName(327, "Icen"),
		models.NewValueName(328, "Spark"),
		models.NewValueName(329, "Heatra"),
		models.NewValueName(330, "Hyper"),
		models.NewValueName(331, "Catastro"),
		models.NewValueName(332, "Leviath"),
		models.NewValueName(333, "Bahamur"),
	}
	ImportantItems = []models.NameValue{
		models.NewValueName(38, "Canoe"),
		models.NewValueName(39, "Nepto Eye"),
		models.NewValueName(40, "Horn of Ice"),
		models.NewValueName(41, "Wheel of Time"),
		models.NewValueName(42, "Noah's Lute"),
		models.NewValueName(43, "Eureka Key"),
		models.NewValueName(44, "Syrcus Key"),
		models.NewValueName(45, "Fang of Water"),
		models.NewValueName(46, "Fang of Wind"),
		models.NewValueName(47, "Fang of Fire"),
		models.NewValueName(48, "Fang of Earth"),
		models.NewValueName(49, "Levigrass Shoes"),
	}
)
