package consts

import (
	"pixel-remastered-save-editor/models"
)

var (
	Items = []models.NameValue{
		models.NewValueName(1, "Potion"),
		models.NewValueName(2, "Hi-Potion"),
		models.NewValueName(3, "Antidote"),
		models.NewValueName(4, "Eye Drops"),
		models.NewValueName(5, "Echo Herbs"),
		models.NewValueName(6, "Gold Needle"),
		models.NewValueName(7, "Maiden's Kiss"),
		models.NewValueName(8, "Mallet"),
		models.NewValueName(9, "Ottershroom"),
		models.NewValueName(10, "Phoenix Down"),
		models.NewValueName(11, "Elixir"),
		models.NewValueName(12, "Gnomish Bread"),
		models.NewValueName(13, "Magic Key"),
		models.NewValueName(14, "Gysahl Greens"),
		models.NewValueName(15, "Antarctic Wind"),
		models.NewValueName(16, "Zeus's Wrath"),
		models.NewValueName(17, "Bomb Fragment"),
		models.NewValueName(18, "Lamia Scale"),
		models.NewValueName(19, "Bacchus's Wine"),
		models.NewValueName(20, "Tranquilizer"),
		models.NewValueName(21, "Bomb Arm"),
		models.NewValueName(22, "Arctic Wind"),
		models.NewValueName(23, "Heavenly Wrath"),
		models.NewValueName(24, "Earthen Drum"),
		models.NewValueName(25, "Turtle Shell"),
		models.NewValueName(26, "Demon's Sigh"),
		models.NewValueName(27, "Black Hole"),
		models.NewValueName(28, "Black Musk"),
		models.NewValueName(29, "Lilith's Kiss"),
		models.NewValueName(30, "Raven's Yawn"),
		models.NewValueName(31, "Shell Breaker"),
		models.NewValueName(32, "Silence Seal"),
		models.NewValueName(33, "Sheep Pillow"),
		models.NewValueName(34, "Shining Curtain"),
		models.NewValueName(35, "Chocobo's Wrath"),
		models.NewValueName(36, "White Musk"),
		models.NewValueName(37, "Canoe"),
		models.NewValueName(38, "Nepto Eye"),
		models.NewValueName(39, "Horn of Ice"),
		models.NewValueName(40, "Wheel of Time"),
		models.NewValueName(41, "Noah's Lute"),
		models.NewValueName(42, "Eureka Key"),
		models.NewValueName(43, "Syrcus Key"),
		models.NewValueName(44, "Fang of Water"),
		models.NewValueName(45, "Fang of Wind"),
		models.NewValueName(46, "Fang of Fire"),
		models.NewValueName(47, "Fang of Earth"),
		models.NewValueName(48, "Levigrass Shoes"),
		models.NewValueName(49, "Cure"),
		models.NewValueName(50, "Poisona"),
		models.NewValueName(51, "Sight"),
		models.NewValueName(52, "Aero"),
		models.NewValueName(53, "Toad"),
		models.NewValueName(54, "Mini"),
		models.NewValueName(55, "Cura"),
		models.NewValueName(56, "Teleport"),
		models.NewValueName(57, "Blindna"),
		models.NewValueName(58, "Libra"),
		models.NewValueName(59, "Confuse"),
		models.NewValueName(60, "Silence"),
		models.NewValueName(61, "Curaga"),
		models.NewValueName(62, "Raise"),
		models.NewValueName(63, "Protect"),
		models.NewValueName(64, "Aeroga"),
		models.NewValueName(65, "Stona"),
		models.NewValueName(66, "Haste"),
		models.NewValueName(67, "Curaja"),
		models.NewValueName(68, "Esuna"),
		models.NewValueName(69, "Reflect"),
		models.NewValueName(70, "Tornado"),
		models.NewValueName(71, "Arise"),
		models.NewValueName(72, "Holy"),
		models.NewValueName(73, "Fire"),
		models.NewValueName(74, "Blizzard"),
		models.NewValueName(75, "Sleep"),
		models.NewValueName(76, "Thunder"),
		models.NewValueName(77, "Poison"),
		models.NewValueName(78, "Blind"),
		models.NewValueName(79, "Fira"),
		models.NewValueName(80, "Blizzara"),
		models.NewValueName(81, "Thundara"),
		models.NewValueName(82, "Break"),
		models.NewValueName(83, "Blizzaga"),
		models.NewValueName(84, "Shade"),
		models.NewValueName(85, "Thundaga"),
		models.NewValueName(86, "Raze"),
		models.NewValueName(87, "Erase"),
		models.NewValueName(88, "Firaga"),
		models.NewValueName(89, "Bio"),
		models.NewValueName(90, "Warp"),
		models.NewValueName(91, "Quake"),
		models.NewValueName(92, "Breakga"),
		models.NewValueName(93, "Drain"),
		models.NewValueName(94, "Flare"),
		models.NewValueName(95, "Death"),
		models.NewValueName(96, "Meteor"),
		models.NewValueName(97, "Escape"),
		models.NewValueName(98, "Icen"),
		models.NewValueName(99, "Spark"),
		models.NewValueName(100, "Heatra"),
		models.NewValueName(101, "Hyper"),
		models.NewValueName(102, "Catastro"),
		models.NewValueName(103, "Leviath"),
		models.NewValueName(104, "Bahamur"),
	}
)
