package consts

import (
	"pixel-remastered-save-editor/models"
)

var Maps = []models.NameValue{
	models.NewValueName(1, "(FC world map)"),
	models.NewValueName(4, "(surface world map)"),
	models.NewValueName(5, "Ur"),
	models.NewValueName(6, "Inn & Item Shop"),
	models.NewValueName(7, "Pub"),
	models.NewValueName(8, "Weapons"),
	models.NewValueName(9, "Armor"),
	models.NewValueName(10, "Magic"),
	models.NewValueName(13, "Kazus"),
	models.NewValueName(14, "Inn & Item Shop"),
	models.NewValueName(15, "Inn & Item Shop 2F"),
	models.NewValueName(16, "Weapons"),
	models.NewValueName(17, "Armor"),
	models.NewValueName(18, "Magic"),
	models.NewValueName(21, "Cid's Airship"),
	models.NewValueName(22, "Castle Sasune"),
	models.NewValueName(23, "1F"),
	models.NewValueName(24, "2F"),
	models.NewValueName(25, "3F"),
	models.NewValueName(26, "Audience Chamber"),
	models.NewValueName(29, "Western Tower 2F"),
	models.NewValueName(30, "Western Tower 3F"),
	models.NewValueName(31, "Western Tower 4F"),
	models.NewValueName(33, "Eastern Tower 2F"),
	models.NewValueName(34, "Eastern Tower 3F"),
	models.NewValueName(35, "Eastern Tower 4F"),
	models.NewValueName(36, "Caanan"),
	models.NewValueName(37, "Inn & Item Shop"),
	models.NewValueName(39, "Weapons"),
	models.NewValueName(40, "Armor"),
	models.NewValueName(41, "Magic"),
	models.NewValueName(45, "Tozus"),
	models.NewValueName(48, "Inn & Item Shop"),
	models.NewValueName(49, "Items"),
	models.NewValueName(50, "Magic"),
	models.NewValueName(51, "Vikings' Cove"),
	models.NewValueName(52, "Inn & Item Shop"),
	models.NewValueName(53, "Inn & Item Shop 2F"),
	models.NewValueName(55, "Tokkul"),
	models.NewValueName(60, "Village of the Ancients"),
	models.NewValueName(61, "Inn & Item Shop"),
	models.NewValueName(63, "Magic"),
	models.NewValueName(64, "Armor"),
	models.NewValueName(65, "Weapons"),
	models.NewValueName(66, "Chocobo Woods"),
	models.NewValueName(67, "Castle Argus"),
	models.NewValueName(68, "1F"),
	models.NewValueName(69, "2F"),
	models.NewValueName(70, "Hall of the Round Table"),
	models.NewValueName(72, "3F"),
	models.NewValueName(75, "Gulgan Gulch"),
	models.NewValueName(76, "B1"),
	models.NewValueName(77, "Gysahl"),
	models.NewValueName(78, "Magic"),
	models.NewValueName(79, "Chocobo Chamber"),
	models.NewValueName(80, "Pub"),
	models.NewValueName(81, "Inn & Item Shop"),
	models.NewValueName(83, "Items"),
	models.NewValueName(84, "Dwarven Hollows"),
	models.NewValueName(86, "Armor"),
	models.NewValueName(87, "Weapons"),
	models.NewValueName(88, "Inn & Item Shop"),
	models.NewValueName(89, "Treasury"),
	models.NewValueName(91, "Living Woods"),
	models.NewValueName(92, "Wrecked Ship"),
	models.NewValueName(95, "Temple of Water"),
	models.NewValueName(97, "Amur"),
	models.NewValueName(100, "Inn & Item Shop"),
	models.NewValueName(101, "Pub"),
	models.NewValueName(102, "Armor"),
	models.NewValueName(103, "Weapons"),
	models.NewValueName(104, "Castle Saronia"),
	models.NewValueName(106, "1F"),
	models.NewValueName(107, "2F"),
	models.NewValueName(108, "Audience Chamber"),
	models.NewValueName(109, "B1"),
	models.NewValueName(115, "Southwestern Saronia"),
	models.NewValueName(116, "Armor"),
	models.NewValueName(119, "Pub"),
	models.NewValueName(120, "Southeastern Saronia"),
	models.NewValueName(121, "Northwestern Saronia"),
	models.NewValueName(122, "Inn & Item Shop"),
	models.NewValueName(123, "Magic"),
	models.NewValueName(124, "Great Library of Saronia"),
	models.NewValueName(125, "Northeastern Saronia"),
	models.NewValueName(126, "Inn & Item Shop"),
	models.NewValueName(127, "Magic"),
	models.NewValueName(128, "Magic"),
	models.NewValueName(129, "Weapons"),
	models.NewValueName(130, "Weapons"),
	models.NewValueName(131, "Doga's Manor"),
	models.NewValueName(134, "Duster"),
	models.NewValueName(135, "Inn & Item Shop"),
	models.NewValueName(136, "Weapons"),
	models.NewValueName(137, "Armor"),
	models.NewValueName(138, "Replito"),
	models.NewValueName(139, "Magic"),
	models.NewValueName(140, "Inn & Item Shop"),
	models.NewValueName(142, "Unei's Shrine"),
	models.NewValueName(143, "The Invincible"),
	models.NewValueName(144, "Falgabard"),
	models.NewValueName(145, "Inn & Item Shop"),
	models.NewValueName(147, "Magic"),
	models.NewValueName(148, "Weapons"),
	models.NewValueName(149, "Armor"),
	models.NewValueName(151, "Doga's Village"),
	models.NewValueName(152, "B3"),
	models.NewValueName(153, "B3"),
	models.NewValueName(154, "B2"),
	models.NewValueName(155, "Wind Crystal"),
	models.NewValueName(156, "Altar Cave"),
	models.NewValueName(157, "The Invincible"),
	models.NewValueName(158, "B2"),
	models.NewValueName(159, "Mythril Mines"),
	models.NewValueName(160, "B2"),
	models.NewValueName(161, "Sealed Cave"),
	models.NewValueName(162, "B2"),
	models.NewValueName(163, "B2"),
	models.NewValueName(164, "B3"),
	models.NewValueName(168, "2F"),
	models.NewValueName(171, "B2"),
	models.NewValueName(172, "B2"),
	models.NewValueName(173, "B3"),
	models.NewValueName(174, "Tower of Owen"),
	models.NewValueName(175, "1F"),
	models.NewValueName(176, "2F"),
	models.NewValueName(177, "3F"),
	models.NewValueName(178, "4F"),
	models.NewValueName(179, "5F"),
	models.NewValueName(180, "6F"),
	models.NewValueName(181, "7F"),
	models.NewValueName(182, "8F"),
	models.NewValueName(183, "9F"),
	models.NewValueName(184, "10F"),
	models.NewValueName(185, "Subterranean Lake"),
	models.NewValueName(187, "B2"),
	models.NewValueName(188, "B3"),
	models.NewValueName(189, "Molten Cave"),
	models.NewValueName(190, "B2"),
	models.NewValueName(193, "Fire Crystal"),
	models.NewValueName(194, "Castle Hein"),
	models.NewValueName(195, "2F"),
	models.NewValueName(196, "2F"),
	models.NewValueName(197, "3F"),
	models.NewValueName(198, "3F"),
	models.NewValueName(199, "3F"),
	models.NewValueName(200, "3F"),
	models.NewValueName(201, "3F"),
	models.NewValueName(202, "3F"),
	models.NewValueName(203, "4F"),
	models.NewValueName(204, "5F"),
	models.NewValueName(205, "5F"),
	models.NewValueName(206, "Cave of Tides"),
	models.NewValueName(208, "B2"),
	models.NewValueName(209, "B3"),
	models.NewValueName(210, "B4"),
	models.NewValueName(211, "Water Crystal"),
	models.NewValueName(212, "Sewers"),
	models.NewValueName(213, "B2"),
	models.NewValueName(214, "B3"),
	models.NewValueName(215, "B4"),
	models.NewValueName(218, "B5"),
	models.NewValueName(219, "Goldor Manor"),
	models.NewValueName(225, "2F"),
	models.NewValueName(226, "3F"),
	models.NewValueName(227, "2F"),
	models.NewValueName(229, "2F"),
	models.NewValueName(230, "3F"),
	models.NewValueName(231, "4F"),
	models.NewValueName(232, "5F"),
	models.NewValueName(233, "6F"),
	models.NewValueName(236, "B5"),
	models.NewValueName(237, "B4"),
	models.NewValueName(238, "Cave of the Circle"),
	models.NewValueName(239, "B2"),
	models.NewValueName(240, "B3"),
	models.NewValueName(241, "B4"),
	models.NewValueName(242, "B1"),
	models.NewValueName(245, "B2"),
	models.NewValueName(246, "B2"),
	models.NewValueName(247, "B2"),
	models.NewValueName(248, "B2"),
	models.NewValueName(249, "B2"),
	models.NewValueName(250, "B3"),
	models.NewValueName(251, "B3"),
	models.NewValueName(252, "B3"),
	models.NewValueName(253, "Ancient Ruins"),
	models.NewValueName(256, "Inn & Item Shop"),
	models.NewValueName(257, "Weapons"),
	models.NewValueName(258, "Armor"),
	models.NewValueName(259, "B2"),
	models.NewValueName(260, "B2"),
	models.NewValueName(261, "B2"),
	models.NewValueName(262, "B2"),
	models.NewValueName(263, "B2"),
	models.NewValueName(264, "B3"),
	models.NewValueName(265, "B4"),
	models.NewValueName(266, "B5"),
	models.NewValueName(267, "B6"),
	models.NewValueName(268, "B8"),
	models.NewValueName(269, "Sunken Cave"),
	models.NewValueName(270, "B2"),
	models.NewValueName(271, "B3"),
	models.NewValueName(272, "Lake Dohr"),
	models.NewValueName(273, "B2"),
	models.NewValueName(274, "B3"),
	models.NewValueName(275, "B4"),
	models.NewValueName(276, "Bahamut's Lair"),
	models.NewValueName(277, "B2"),
	models.NewValueName(278, "B3"),
	models.NewValueName(279, "Falgabard Cave"),
	models.NewValueName(280, "Cave of Shadows"),
	models.NewValueName(282, "B2"),
	models.NewValueName(283, "B3"),
	models.NewValueName(284, "B3"),
	models.NewValueName(285, "B3"),
	models.NewValueName(286, "B4"),
	models.NewValueName(287, "B5"),
	models.NewValueName(288, "B6"),
	models.NewValueName(289, "B7"),
	models.NewValueName(290, "B8"),
	models.NewValueName(291, "Doga's Grotto"),
	models.NewValueName(293, "B2"),
	models.NewValueName(294, "B2"),
	models.NewValueName(295, "B2"),
	models.NewValueName(296, "B2"),
	models.NewValueName(297, "B3"),
	models.NewValueName(298, "B3"),
	models.NewValueName(300, "Earth Crystal"),
	models.NewValueName(305, "Crystal Tower"),
	models.NewValueName(307, "2F"),
	models.NewValueName(308, "3F"),
	models.NewValueName(309, "4F"),
	models.NewValueName(310, "5F"),
	models.NewValueName(311, "6F"),
	models.NewValueName(312, "7F"),
	models.NewValueName(316, "B2"),
	models.NewValueName(317, "B2"),
	models.NewValueName(318, "B2"),
	models.NewValueName(319, "B3"),
	models.NewValueName(320, "B4"),
	models.NewValueName(321, "B5"),
	models.NewValueName(322, "B6"),
	models.NewValueName(323, "B7"),
	models.NewValueName(324, "B7"),
	models.NewValueName(325, "World of Darkness"),
	models.NewValueName(327, "Dark Wind Crystal"),
	models.NewValueName(329, "Dark Fire Crystal"),
	models.NewValueName(331, "Dark Water Crystal"),
	models.NewValueName(333, "Dark Earth Crystal"),
	models.NewValueName(342, "The Invincible"),
}
