package consts

import (
	"pixel-remastered-save-editor/models"
)

var (
	Weapons = []models.NameValue{
		models.NewValueName(1, "[Empty]"),
		models.NewValueName(2, "Knife"),
		models.NewValueName(3, "Dagger"),
		models.NewValueName(4, "Mythril Knife"),
		models.NewValueName(5, "Main Gauche"),
		models.NewValueName(6, "Orichalcum"),
		models.NewValueName(7, "Air Knife"),
		models.NewValueName(8, "Golden Sword"),
		models.NewValueName(9, "Longsword"),
		models.NewValueName(10, "Wightslayer"),
		models.NewValueName(11, "Mythril Sword"),
		models.NewValueName(12, "Serpent Sword"),
		models.NewValueName(13, "Tyrfing"),
		models.NewValueName(14, "Salamand Sword"),
		models.NewValueName(15, "Freezing Blade"),
		models.NewValueName(16, "Royal Sword"),
		models.NewValueName(17, "Blood Sword"),
		models.NewValueName(18, "Ancient Sword"),
		models.NewValueName(19, "Defender"),
		models.NewValueName(20, "Break Blade"),
		models.NewValueName(21, "Excalibur"),
		models.NewValueName(22, "Ragnarok"),
		models.NewValueName(23, "Onion Sword"),
		models.NewValueName(24, "Ashura"),
		models.NewValueName(25, "Kotetsu"),
		models.NewValueName(26, "Kiku-Ichimonji"),
		models.NewValueName(27, "Masamune"),
		models.NewValueName(28, "Staff"),
		models.NewValueName(29, "Fire Staff"),
		models.NewValueName(30, "Ice Staff"),
		models.NewValueName(31, "Light Staff"),
		models.NewValueName(32, "Golem Staff"),
		models.NewValueName(33, "Rune Staff"),
		models.NewValueName(34, "Elder Staff"),
		models.NewValueName(35, "Mythril Rod"),
		models.NewValueName(36, "Ice Rod"),
		models.NewValueName(37, "Light Rod"),
		models.NewValueName(38, "Fire Rod"),
		models.NewValueName(39, "Omnirod"),
		models.NewValueName(40, "Bow"),
		models.NewValueName(41, "Great Bow"),
		models.NewValueName(42, "Killer Bow"),
		models.NewValueName(43, "Rune Bow"),
		models.NewValueName(44, "Yoichi Bow"),
		models.NewValueName(45, "Wooden Arrow"),
		models.NewValueName(46, "Holy Arrow"),
		models.NewValueName(47, "Iron Arrow"),
		models.NewValueName(48, "Ice Arrow"),
		models.NewValueName(49, "Fire Arrow"),
		models.NewValueName(50, "Light Arrow"),
		models.NewValueName(51, "Medusa Arrow"),
		models.NewValueName(52, "Yoichi Arrow"),
		models.NewValueName(53, "Book of Ice"),
		models.NewValueName(54, "Book of Light"),
		models.NewValueName(55, "Book of Fire"),
		models.NewValueName(56, "Tome of Ice"),
		models.NewValueName(57, "Tome of Light"),
		models.NewValueName(58, "Tome of Fire"),
		models.NewValueName(59, "Nunchaku"),
		models.NewValueName(60, "Tonfa"),
		models.NewValueName(61, "Sansetsukon"),
		models.NewValueName(62, "Cat Claws"),
		models.NewValueName(63, "Kaiser Knuckles"),
		models.NewValueName(64, "Wyvern Claws"),
		models.NewValueName(65, "Faerie Claws"),
		models.NewValueName(66, "Hellish Claws"),
		models.NewValueName(67, "Thorian Hammer"),
		models.NewValueName(68, "Morning Star"),
		models.NewValueName(69, "Triton Hammer"),
		models.NewValueName(70, "Battleaxe"),
		models.NewValueName(71, "Dual Tomahawk"),
		models.NewValueName(72, "Dual Haken"),
		models.NewValueName(73, "Thunder Spear"),
		models.NewValueName(74, "Wind Spear"),
		models.NewValueName(75, "Blood Lance"),
		models.NewValueName(76, "Holy Lance"),
		models.NewValueName(77, "Boomerang"),
		models.NewValueName(78, "Moonring Blade"),
		models.NewValueName(79, "Shuriken"),
		models.NewValueName(80, "Diamond Bell"),
		models.NewValueName(81, "Earthen Bell"),
		models.NewValueName(82, "Rune Bell"),
		models.NewValueName(83, "Madhura Harp"),
		models.NewValueName(84, "Lamia Harp"),
		models.NewValueName(85, "Loki Harp"),
	}
)
