package consts

import (
	"pixel-remastered-save-editor/models"
)

var (
	Abilities = []models.NameValue{
		models.NewValueName(5, "Cure"),
		models.NewValueName(6, "Protect"),
		models.NewValueName(7, "Dia"),
		models.NewValueName(8, "Blink"),
		models.NewValueName(9, "Fire"),
		models.NewValueName(10, "Focus"),
		models.NewValueName(11, "Sleep"),
		models.NewValueName(12, "Thunder"),
		models.NewValueName(13, "Blindna"),
		models.NewValueName(14, "Silence"),
		models.NewValueName(15, "Invis"),
		models.NewValueName(16, "NulShock"),
		models.NewValueName(17, "Blizzard"),
		models.NewValueName(18, "Temper"),
		models.NewValueName(19, "Dark"),
		models.NewValueName(20, "Slow"),
		models.NewValueName(21, "Cura"),
		models.NewValueName(22, "NulBlaze"),
		models.NewValueName(23, "Diara"),
		models.NewValueName(24, "Heal"),
		models.NewValueName(25, "Fira"),
		models.NewValueName(26, "Thundara"),
		models.NewValueName(27, "Hold"),
		models.NewValueName(28, "Focara"),
		models.NewValueName(29, "Poisona"),
		models.NewValueName(30, "NulFrost"),
		models.NewValueName(31, "Fear"),
		models.NewValueName(32, "Vox"),
		models.NewValueName(33, "Sleepra"),
		models.NewValueName(34, "Confuse"),
		models.NewValueName(35, "Haste"),
		models.NewValueName(36, "Blizzara"),
		models.NewValueName(37, "Curaga"),
		models.NewValueName(38, "Diaga"),
		models.NewValueName(39, "Life"),
		models.NewValueName(40, "Healara"),
		models.NewValueName(41, "Firaga"),
		models.NewValueName(42, "Teleport"),
		models.NewValueName(43, "Scourge"),
		models.NewValueName(44, "Slowra"),
		models.NewValueName(45, "Stona"),
		models.NewValueName(46, "Protera"),
		models.NewValueName(47, "Exit"),
		models.NewValueName(48, "Invisira"),
		models.NewValueName(49, "Thundaga"),
		models.NewValueName(50, "Quake"),
		models.NewValueName(51, "Death"),
		models.NewValueName(52, "Stun"),
		models.NewValueName(53, "Curaja"),
		models.NewValueName(54, "NulDeath"),
		models.NewValueName(55, "Diaja"),
		models.NewValueName(56, "Healaga"),
		models.NewValueName(57, "Blizzaga"),
		models.NewValueName(58, "Saber"),
		models.NewValueName(59, "Break"),
		models.NewValueName(60, "Blind"),
		models.NewValueName(61, "Full-Life"),
		models.NewValueName(62, "NulAll"),
		models.NewValueName(63, "Holy"),
		models.NewValueName(64, "Dispel"),
		models.NewValueName(65, "Flare"),
		models.NewValueName(66, "Stop"),
		models.NewValueName(67, "Warp"),
		models.NewValueName(68, "Kill"),
		models.NewValueName(69, "Icestorm"),
		models.NewValueName(70, "Blaze"),
		models.NewValueName(71, "Gaze"),
		models.NewValueName(72, "Gaze"),
		models.NewValueName(73, "Flash"),
		models.NewValueName(74, "Blaze"),
		models.NewValueName(75, "Earthquake"),
		models.NewValueName(76, "Gaze"),
		models.NewValueName(77, "Gaze"),
		models.NewValueName(78, "Gaze"),
		models.NewValueName(79, "Icestorm"),
		models.NewValueName(80, "Blaze"),
		models.NewValueName(81, "Blaze"),
		models.NewValueName(82, "Blaze"),
		models.NewValueName(83, "Stone Gas"),
		models.NewValueName(84, "Mind Blast"),
		models.NewValueName(85, "Poison Gas"),
		models.NewValueName(86, "Thunderbolt"),
		models.NewValueName(87, "Deadly Gas"),
		models.NewValueName(88, "Snort"),
		models.NewValueName(89, "Nuke"),
		models.NewValueName(90, "Ink"),
		models.NewValueName(91, "Poison Darts"),
		models.NewValueName(92, "Gaze"),
		models.NewValueName(93, "Tsunami"),
		models.NewValueName(94, "Cyclone"),
	}
)
