package consts

import (
	"pixel-remastered-save-editor/models"
)

var Maps = []models.NameValue{
	models.NewNameValue("World Map", 1),
	models.NewNameValue("Castle Cornelia 1F", 2),
	models.NewNameValue("Castle Cornelia 2F", 3),
	models.NewNameValue("Cornelia", 4),
	models.NewNameValue("Cornelia - Inn", 5),
	models.NewNameValue("Cornelia - Items", 6),
	models.NewNameValue("Cornelia - Weapons", 7),
	models.NewNameValue("Cornelia - Armor", 8),
	models.NewNameValue("Cornelia - Sanctuary", 9),
	models.NewNameValue("Cornelia - White Magic", 10),
	models.NewNameValue("Cornelia - Black Magic", 11),
	models.NewNameValue("Matoya's Cave", 12),
	models.NewNameValue("Pravoka", 13),
	models.NewNameValue("Pravoka - Inn", 14),
	models.NewNameValue("Pravoka - Items", 15),
	models.NewNameValue("Pravoka - Weapons", 16),
	models.NewNameValue("Pravoka - Armor", 17),
	models.NewNameValue("Pravoka - Sanctuary", 18),
	models.NewNameValue("Pravoka - White Magic", 19),
	models.NewNameValue("Pravoka - Black Magic", 20),
	models.NewNameValue("Mount Duergar", 21),
	models.NewNameValue("Elfheim", 22),
	models.NewNameValue("Elfheim - Inn", 23),
	models.NewNameValue("Elfheim - Items", 24),
	models.NewNameValue("Elfheim - Weapons", 25),
	models.NewNameValue("Elfheim - Armor", 26),
	models.NewNameValue("Elfheim - Sanctuary", 27),
	models.NewNameValue("Elfheim - White Magic", 28),
	models.NewNameValue("Elfheim - Black Magic", 29),
	models.NewNameValue("Elfheim - White Magic", 30),
	models.NewNameValue("Elfheim - Black Magic", 31),
	models.NewNameValue("Elven Castle", 32),
	models.NewNameValue("Western Keep", 33),
	models.NewNameValue("Melmond", 34),
	models.NewNameValue("Melmond - Inn", 35),
	models.NewNameValue("Melmond - Weapons", 36),
	models.NewNameValue("Melmond - Armor", 37),
	models.NewNameValue("Melmond - White Magic", 38),
	models.NewNameValue("Melmond - Black Magic", 39),
	models.NewNameValue("Sage's Cave", 40),
	models.NewNameValue("Crescent Lake", 41),
	models.NewNameValue("Crescent Lake - Inn", 42),
	models.NewNameValue("Crescent Lake - Items", 43),
	models.NewNameValue("Crescent Lake - Weapons", 44),
	models.NewNameValue("Crescent Lake - Armor", 45),
	models.NewNameValue("Crescent Lake - Sanctuary", 46),
	models.NewNameValue("Crescent Lake - White Magic", 47),
	models.NewNameValue("Crescent Lake - Black Magic", 48),
	models.NewNameValue("Dragon Caves", 49),
	models.NewNameValue("Dragon Caves", 50),
	models.NewNameValue("Dragon Caves", 51),
	models.NewNameValue("Onrac", 52),
	models.NewNameValue("Onrac - Inn", 53),
	models.NewNameValue("Onrac - Items", 54),
	models.NewNameValue("Onrac - Sanctuary", 55),
	models.NewNameValue("Onrac - White Magic", 56),
	models.NewNameValue("Onrac - Black Magic", 57),
	models.NewNameValue("Caravan", 58),
	models.NewNameValue("Caravan - Items", 59),
	models.NewNameValue("Gaia", 60),
	models.NewNameValue("Gaia - Inn", 61),
	models.NewNameValue("Gaia - Items", 62),
	models.NewNameValue("Gaia", 63),
	models.NewNameValue("Gaia", 64),
	models.NewNameValue("Gaia - Sanctuary", 65),
	models.NewNameValue("Gaia - White Magic", 66),
	models.NewNameValue("Gaia - Black Magic", 67),
	models.NewNameValue("Gaia", 68),
	models.NewNameValue("Gaia", 69),
	models.NewNameValue("Lufenia", 70),
	models.NewNameValue("Lufenia - Magic Shop", 71),
	models.NewNameValue("Chaos Shrine", 72),
	models.NewNameValue("Marsh Cave - B1", 73),
	models.NewNameValue("Marsh Cave - B2", 74),
	models.NewNameValue("Marsh Cave - B3", 75),
	models.NewNameValue("Cavern of Earth - B1", 76),
	models.NewNameValue("Cavern of Earth - B2", 77),
	models.NewNameValue("Cavern of Earth - B3", 78),
	models.NewNameValue("Cavern of Earth - B4", 79),
	models.NewNameValue("Cavern of Earth - B5", 80),
	models.NewNameValue("Giant's Cave", 81),
	models.NewNameValue("Mount Gulg - B1", 82),
	models.NewNameValue("Mount Gulg - B2", 83),
	models.NewNameValue("Mount Gulg - B3", 84),
	models.NewNameValue("Mount Gulg - B3", 85),
	models.NewNameValue("Mount Gulg - B4", 86),
	models.NewNameValue("Mount Gulg - B5", 87),
	models.NewNameValue("Cavern of Ice - B1", 88),
	models.NewNameValue("Cavern of Ice - B2", 89),
	models.NewNameValue("Cavern of Ice - B3", 90),
	models.NewNameValue("Cavern of Ice - B2", 91),
	models.NewNameValue("Cavern of Ice - B3", 92),
	models.NewNameValue("Citadel of Trials - 1F", 93),
	models.NewNameValue("Citadel of Trials - 2F", 94),
	models.NewNameValue("Citadel of Trials - 3F", 95),
	models.NewNameValue("Sunken Shrine - 1F", 96),
	models.NewNameValue("Sunken Shrine - 2F", 97),
	models.NewNameValue("Sunken Shrine - 3F", 98),
	models.NewNameValue("Sunken Shrine - 3F", 99),
	models.NewNameValue("Sunken Shrine - 3F", 100),
	models.NewNameValue("Sunken Shrine - 4F", 101),
	models.NewNameValue("Sunken Shrine - 4F", 102),
	models.NewNameValue("Sunken Shrine - 5F", 103),
	models.NewNameValue("Waterfall Cavern", 104),
	models.NewNameValue("Mirage Tower - 1F", 105),
	models.NewNameValue("Mirage Tower - 2F", 106),
	models.NewNameValue("Mirage Tower - 3F", 107),
	models.NewNameValue("Flying Fortress - 1F", 108),
	models.NewNameValue("Flying Fortress - 2F", 109),
	models.NewNameValue("Flying Fortress - 3F", 110),
	models.NewNameValue("Flying Fortress - 4F", 111),
	models.NewNameValue("Flying Fortress - 5F", 112),
	models.NewNameValue("Chaos Shrine - 1F", 113),
	models.NewNameValue("Chaos Shrine - 2F", 114),
	models.NewNameValue("Chaos Shrine - 3F", 115),
	models.NewNameValue("Chaos Shrine - B1", 116),
	models.NewNameValue("Chaos Shrine - B2", 117),
	models.NewNameValue("Chaos Shrine - B3", 118),
	models.NewNameValue("Chaos Shrine - B4", 119),
	models.NewNameValue("Chaos Shrine - B5", 120),
}
