package consts

import (
	"pixel-remastered-save-editor/models"
)

var (
	Shields = []models.NameValue{
		models.NewValueName(224, "[Empty L. Hand]"),
		models.NewValueName(228, "Iron Shield"),
		models.NewValueName(229, "Dark Shield"),
		models.NewValueName(230, "Demon Shield"),
		models.NewValueName(231, "Light Shield"),
		models.NewValueName(232, "Mythril Shield"),
		models.NewValueName(233, "Fire Shield"),
		models.NewValueName(234, "Ice Shield"),
		models.NewValueName(235, "Diamond Shield"),
		models.NewValueName(236, "Aegis Shield"),
		models.NewValueName(237, "Genji Shield"),
		models.NewValueName(238, "Dragon Shield"),
		models.NewValueName(239, "Crystal Shield"),
	}
	Armors = []models.NameValue{
		models.NewValueName(225, "[Empty Body]"),
		models.NewValueName(262, "Clothes"),
		models.NewValueName(263, "Prisoners' Wear"),
		models.NewValueName(264, "Leather Garb"),
		models.NewValueName(265, "Bard's Tunic"),
		models.NewValueName(266, "Gaia Gear"),
		models.NewValueName(267, "Iron Armor"),
		models.NewValueName(268, "Dark Armor"),
		models.NewValueName(269, "Sage's Surplice"),
		models.NewValueName(270, "Kenpogi"),
		models.NewValueName(271, "Hades Armor"),
		models.NewValueName(272, "Black Robe"),
		models.NewValueName(273, "Demon Armor"),
		models.NewValueName(274, "Black Belt"),
		models.NewValueName(275, "Knight's Armor"),
		models.NewValueName(276, "Light Robe"),
		models.NewValueName(277, "Mythril Armor"),
		models.NewValueName(278, "Flame Mail"),
		models.NewValueName(279, "Power Vest"),
		models.NewValueName(280, "Ice Armor"),
		models.NewValueName(281, "White Robe"),
		models.NewValueName(282, "Diamond Armor"),
		models.NewValueName(283, "Minerva's Plate"),
		models.NewValueName(284, "Genji Armor"),
		models.NewValueName(285, "Dragon Mail"),
		models.NewValueName(286, "Black Garb"),
		models.NewValueName(287, "Crystal Mail"),
		models.NewValueName(288, "Adamant Armor"),
	}
	Helmets = []models.NameValue{
		models.NewValueName(226, "[Empty Head]"),
		models.NewValueName(241, "Leather Cap"),
		models.NewValueName(242, "Twist Headband"),
		models.NewValueName(243, "Feathered Cap"),
		models.NewValueName(244, "Iron Helm"),
		models.NewValueName(245, "Wizard's Hat"),
		models.NewValueName(246, "Green Beret"),
		models.NewValueName(247, "Dark Helm"),
		models.NewValueName(248, "Hades Helm"),
		models.NewValueName(249, "Sage's Miter"),
		models.NewValueName(250, "Black Cowl"),
		models.NewValueName(251, "Demon Helm"),
		models.NewValueName(252, "Light Helm"),
		models.NewValueName(253, "Gold Hairpin"),
		models.NewValueName(254, "Mythril Helm"),
		models.NewValueName(255, "Diamond Helm"),
		models.NewValueName(256, "Ribbon"),
		models.NewValueName(257, "Genji Helm"),
		models.NewValueName(258, "Dragon Helm"),
		models.NewValueName(259, "Crystal Helm"),
		models.NewValueName(260, "Glass Mask"),
	}
	Hands = []models.NameValue{
		models.NewValueName(227, "[Empty Arms]"),
		models.NewValueName(290, "Ruby Ring"),
		models.NewValueName(291, "Cursed Ring"),
		models.NewValueName(292, "Iron Gloves"),
		models.NewValueName(293, "Dark Gloves"),
		models.NewValueName(294, "Iron Armlet"),
		models.NewValueName(295, "Power Armlet"),
		models.NewValueName(296, "Hades Gloves"),
		models.NewValueName(297, "Demon Gloves"),
		models.NewValueName(298, "Silver Armlet"),
		models.NewValueName(299, "Gauntlets"),
		models.NewValueName(300, "Rune Armlet"),
		models.NewValueName(301, "Mythril Gloves"),
		models.NewValueName(302, "Diamond Armlet"),
		models.NewValueName(303, "Diamond Gloves"),
		models.NewValueName(304, "Genji Gloves"),
		models.NewValueName(305, "Dragon Gloves"),
		models.NewValueName(306, "Giant's Gloves"),
		models.NewValueName(307, "Crystal Gloves"),
		models.NewValueName(308, "Protect Ring"),
		models.NewValueName(309, "Crystal Ring"),
	}
)
