package consts

import (
	"pixel-remastered-save-editor/models"
)

var (
	Items = []models.NameValue{
		models.NewValueName(2, "Potion"),
		models.NewValueName(3, "Hi-Potion"),
		models.NewValueName(4, "X-Potion"),
		models.NewValueName(5, "Ether"),
		models.NewValueName(6, "Dry Ether"),
		models.NewValueName(7, "Elixir"),
		models.NewValueName(9, "Phoenix Down"),
		models.NewValueName(10, "Gold Needle"),
		models.NewValueName(11, "Maiden's Kiss"),
		models.NewValueName(12, "Mallet"),
		models.NewValueName(13, "Diet Food"),
		models.NewValueName(14, "Echo Herbs"),
		models.NewValueName(15, "Eye Drops"),
		models.NewValueName(16, "Antidote"),
		models.NewValueName(17, "Cross"),
		models.NewValueName(18, "Remedy"),
		models.NewValueName(19, "Alarm Clock"),
		models.NewValueName(20, "Unicorn Horn"),
		models.NewValueName(21, "Tent"),
		models.NewValueName(22, "Cottage"),
		models.NewValueName(23, "Emergency Exit"),
		models.NewValueName(24, "Dwarven Bread"),
		models.NewValueName(25, "Gysahl Greens"),
		models.NewValueName(26, "Gysahl Whistle"),
		models.NewValueName(27, "Golden Apple"),
		models.NewValueName(28, "Silver Apple"),
		models.NewValueName(29, "Soma Drop"),
		// models.NewValueName(,"Siren"),
		// models.NewValueName(,"Red Fang"),
		// models.NewValueName(,"White Fang"),
		// models.NewValueName(,"Blue Fang"),
		models.NewValueName(36, "Bomb Fragment"),
		models.NewValueName(37, "Bomb Arm"),
		models.NewValueName(38, "Antarctic Wind"),
		models.NewValueName(39, "Arctic Wind"),
		models.NewValueName(40, "Rage of Zeus"),
		models.NewValueName(39, "Rage of the Gods"),
		// models.NewValueName(,"Gaia Drum"),
		models.NewValueName(43, "Bomb Core"),
		models.NewValueName(44, "Stardust"),
		models.NewValueName(45, "Lilith's Kiss"),
		models.NewValueName(46, "Vampire Fang"),
		models.NewValueName(47, "Spider's Silk"),
		models.NewValueName(48, "Bell of Silence"),
		models.NewValueName(49, "Coeurl's Whisker"),
		models.NewValueName(50, "Bestiary"),
		models.NewValueName(51, "Hourglass"),
		models.NewValueName(52, "Silver Hourglass"),
		models.NewValueName(53, "Gold Hourglass"),
		models.NewValueName(54, "Bacchus's Cider"),
		models.NewValueName(55, "Hermes Shoes"),
		models.NewValueName(56, "Decoy"),
		models.NewValueName(57, "Light Curtain"),
		models.NewValueName(58, "Lunar Curtain"),
		models.NewValueName(59, "Crystal"),
		models.NewValueName(60, "Membership Pass"),
		// models.NewValueName(,"Goblin"),
		// models.NewValueName(,"Bomb"),
		// models.NewValueName(,"Cockatrice"),
		// models.NewValueName(,"Mind Flayer"),
		// models.NewValueName(,"Grimoire"),
	}
	ImportantItems = []models.NameValue{
		models.NewValueName(62, "Frying Pan"),
		models.NewValueName(63, "Adamantite"),
		models.NewValueName(64, "Sand Ruby"),
		models.NewValueName(65, "Dark Matter"),
		models.NewValueName(66, "Earth Crystal"),
		models.NewValueName(67, "Rat Tail"),
		models.NewValueName(68, "Baron Key"),
		models.NewValueName(69, "Twin Harp"),
		models.NewValueName(70, "Pink Tail"),
		models.NewValueName(71, "Bomb Ring"),
		models.NewValueName(72, "Magma Rock"),
		models.NewValueName(73, "Dark Crystal"),
		models.NewValueName(74, "Luca's Necklace"),
		models.NewValueName(75, "Dr. Lugae's Key"),
	}
)
