package consts

import (
	"pixel-remastered-save-editor/models"
)

var (
	Weapons = []models.NameValue{
		models.NewValueName(127, "[Empty Hand]"),
		models.NewValueName(128, "Dark Sword"),
		models.NewValueName(129, "Shadowblade"),
		models.NewValueName(130, "Deathbringer"),
		models.NewValueName(131, "Sword of Legend"),
		models.NewValueName(132, "Light Sword"),
		models.NewValueName(133, "Excalibur"),
		models.NewValueName(134, "Ragnarok"),
		models.NewValueName(135, "Ancient Sword"),
		models.NewValueName(136, "Blood Sword"),
		models.NewValueName(137, "Mythril Sword"),
		models.NewValueName(138, "Sleep Blade"),
		models.NewValueName(139, "Flame Sword"),
		models.NewValueName(140, "Icebrand"),
		models.NewValueName(141, "Gorgon Blade"),
		models.NewValueName(142, "Avenger"),
		models.NewValueName(147, "Defender"),
		models.NewValueName(148, "Spear"),
		models.NewValueName(149, "Wind Spear"),
		models.NewValueName(150, "Fire Lance"),
		models.NewValueName(151, "Ice Lance"),
		models.NewValueName(152, "Blood Lance"),
		models.NewValueName(153, "Gungnir"),
		models.NewValueName(154, "Wyvern Lance"),
		models.NewValueName(155, "Holy Lance"),
		models.NewValueName(156, "Mythril Knife"),
		models.NewValueName(157, "Dancing Dagger"),
		models.NewValueName(158, "Mage Masher"),
		models.NewValueName(159, "Knife"),
		models.NewValueName(160, "Dreamer's Harp"),
		models.NewValueName(161, "Lamia Harp"),
		models.NewValueName(162, "Flame Claw"),
		models.NewValueName(163, "Ice Claw"),
		models.NewValueName(164, "Lightning Claw"),
		models.NewValueName(165, "Fairy Claw"),
		models.NewValueName(166, "Hell Claw"),
		models.NewValueName(167, "Cat Claw"),
		models.NewValueName(168, "Wooden Hammer"),
		models.NewValueName(169, "Mythril Hammer"),
		models.NewValueName(170, "Gaia Hammer"),
		models.NewValueName(171, "Dwarf Axe"),
		models.NewValueName(172, "Ogrekiller"),
		models.NewValueName(173, "Poison Axe"),
		models.NewValueName(174, "Rune Axe"),
		models.NewValueName(175, "Kunai"),
		models.NewValueName(176, "Ashura"),
		models.NewValueName(177, "Kotetsu"),
		models.NewValueName(178, "Kikuichimonji"),
		models.NewValueName(179, "Murasame"),
		models.NewValueName(180, "Masamune"),
		models.NewValueName(181, "Rod"),
		models.NewValueName(182, "Flame Rod"),
		models.NewValueName(183, "Ice Rod"),
		models.NewValueName(184, "Thunder Rod"),
		models.NewValueName(185, "Rod of Lilith"),
		models.NewValueName(186, "Rod of Change"),
		models.NewValueName(187, "Fairy Rod"),
		models.NewValueName(188, "Stardust Rod"),
		models.NewValueName(189, "Staff"),
		models.NewValueName(190, "Healing Staff"),
		models.NewValueName(191, "Mythril Staff"),
		models.NewValueName(192, "Power Staff"),
		models.NewValueName(193, "Kinesis Staff"),
		models.NewValueName(194, "Sage Staff"),
		models.NewValueName(195, "Rune Staff"),
		models.NewValueName(196, "Bow"),
		models.NewValueName(197, "Great Bow"),
		models.NewValueName(198, "Killer Bow"),
		models.NewValueName(199, "Elven Bow"),
		models.NewValueName(200, "Yoichi Bow"),
		models.NewValueName(201, "Artemis Bow"),
		models.NewValueName(203, "Medusa Arrow"),
		models.NewValueName(204, "Iron Arrow"),
		models.NewValueName(205, "Holy Arrow"),
		models.NewValueName(206, "Fire Arrow"),
		models.NewValueName(207, "Ice Arrow"),
		models.NewValueName(208, "Thunder Arrow"),
		models.NewValueName(209, "Dark Arrow"),
		models.NewValueName(210, "Poison Arrow"),
		models.NewValueName(211, "Mute Arrow"),
		models.NewValueName(212, "Angel Arrow"),
		models.NewValueName(213, "Yoichi Arrow"),
		models.NewValueName(214, "Artemis Arrow"),
		models.NewValueName(215, "Whip"),
		models.NewValueName(216, "Chain Whip"),
		models.NewValueName(219, "Blitz Whip"),
		models.NewValueName(218, "Fire Whip"),
		models.NewValueName(219, "Dragon Whisker"),
		models.NewValueName(220, "Boomerang"),
		models.NewValueName(221, "Full Moon"),
		models.NewValueName(222, "Shuriken"),
		models.NewValueName(223, "Fuma Shuriken"),
		models.NewValueName(521, "Crossbow"),
	}
)
