package consts

import (
	"pixel-remastered-save-editor/models"
)

const (
	BlitzFrom   int64 = 132
	BlitzTo     int64 = 139
	BushidoFrom int64 = 124
	BushidoTo   int64 = 131
	DanceFrom   int64 = 164
	DanceTo     int64 = 171
	LoreFrom    int64 = 140
	LoreTo      int64 = 163
	RageFrom    int64 = 800
	RageTo      int64 = 1055
)

var (
	Blitzes = []models.NameValue{
		models.NewNameValue("Raging Fist", 132),
		models.NewNameValue("Aura Cannon", 133),
		models.NewNameValue("Meteor Strike", 134),
		models.NewNameValue("Rising Phoenix", 135),
		models.NewNameValue("Chakra", 136),
		models.NewNameValue("Razor Gale", 137),
		models.NewNameValue("Soul Spiral", 138),
		models.NewNameValue("Phantom Rush", 139),
	}
	Bushidos = []models.NameValue{
		models.NewNameValue("Fang", 124),
		models.NewNameValue("Sky", 125),
		models.NewNameValue("Tiger", 126),
		models.NewNameValue("Flurry", 127),
		models.NewNameValue("Dragon", 128),
		models.NewNameValue("Eclipse", 129),
		models.NewNameValue("Tempest", 130),
		models.NewNameValue("Oblivion", 131),
	}
	Dances = []models.NameValue{
		models.NewNameValue("Wind Rhapsody", 164),
		models.NewNameValue("Forest Nocturne", 165),
		models.NewNameValue("Desert Lullaby", 166),
		models.NewNameValue("Love Serenade", 167),
		models.NewNameValue("Earth Blues", 168),
		models.NewNameValue("Water Harmony", 169),
		models.NewNameValue("Twilight Requiem", 170),
		models.NewNameValue("Snowman Rondo", 171),
	}
	Lores = []models.NameValue{
		models.NewNameValue("Doom", 140),
		models.NewNameValue("Roulette", 141),
		models.NewNameValue("Tsunami", 142),
		models.NewNameValue("Aqua Breath", 143),
		models.NewNameValue("Aero", 144),
		models.NewNameValue("1000 Needles", 145),
		models.NewNameValue("Mighty Guard", 146),
		models.NewNameValue("Revenge Blast", 147),
		models.NewNameValue("White Wind", 148),
		models.NewNameValue("Lv. 5 Death", 149),
		models.NewNameValue("Lv. 4 Flare", 150),
		models.NewNameValue("Lv. 3 Confuse", 151),
		models.NewNameValue("Reflect ???", 152),
		models.NewNameValue("Lv. ? Holy", 153),
		models.NewNameValue("Traveler", 154),
		models.NewNameValue("Force Field", 155),
		models.NewNameValue("Dischord", 156),
		models.NewNameValue("Bad Breath", 157),
		models.NewNameValue("Transfusion", 158),
		models.NewNameValue("Rippler", 159),
		models.NewNameValue("Stone", 160),
		models.NewNameValue("Quasar", 161),
		models.NewNameValue("Grand Delta", 162),
		models.NewNameValue("Self-Destruct", 163),
	}
	Rages = []models.NameValue{
		models.NewValueName(800, "Guard"),
		models.NewValueName(801, "Imperial Soldier"),
		models.NewValueName(802, "Templar"),
		models.NewValueName(803, "Ninja"),
		models.NewValueName(804, "Samurai"),
		models.NewValueName(805, "Borghese"),
		models.NewValueName(806, "Magna Roader"),
		models.NewValueName(807, "Yojimbo"),
		models.NewValueName(808, "Cloud"),
		models.NewValueName(809, "Misty"),
		models.NewValueName(810, "Al Jabr"),
		models.NewValueName(811, "Zaghrem"),
		models.NewValueName(812, "Apocrypha"),
		models.NewValueName(813, "Dark Force"),
		models.NewValueName(814, "Angel Whisper"),
		models.NewValueName(815, "Oversoul"),
		models.NewValueName(816, "Skeletal Horror"),
		models.NewValueName(817, "Commander"),
		models.NewValueName(818, "Mu"),
		models.NewValueName(819, "Wererat"),
		models.NewValueName(820, "Mugbear"),
		models.NewValueName(821, "Belmodar"),
		models.NewValueName(822, "Muud Suud"),
		models.NewValueName(823, "Leaf Bunny"),
		models.NewValueName(824, "Stray Cat"),
		models.NewValueName(825, "Silver Lobo"),
		models.NewValueName(826, "Doberman"),
		models.NewValueName(827, "Megalodoth"),
		models.NewValueName(828, "Fidor"),
		models.NewValueName(829, "Briareus"),
		models.NewValueName(830, "Suriander"),
		models.NewValueName(831, "Chimera"),
		models.NewValueName(832, "Behemoth"),
		models.NewValueName(833, "Fafnir"),
		models.NewValueName(834, "Lesser Lopros"),
		models.NewValueName(835, "Fossil Dragon"),
		models.NewValueName(836, "Holy Dragon"),
		models.NewValueName(837, "Fiend Dragon"),
		models.NewValueName(838, "Brachiosaur"),
		models.NewValueName(839, "Tyrannosaur"),
		models.NewValueName(840, "Darkwind"),
		models.NewValueName(841, "Aepyornis"),
		models.NewValueName(842, "Vulture"),
		models.NewValueName(843, "Vasegiatta"),
		models.NewValueName(844, "Zokka"),
		models.NewValueName(845, "Trapper"),
		models.NewValueName(846, "Hornet"),
		models.NewValueName(847, "Nettlehopper"),
		models.NewValueName(848, "Delta Beetle"),
		models.NewValueName(849, "Killer Mantis"),
		models.NewValueName(850, "Trillium"),
		models.NewValueName(851, "Rafflesia"),
		models.NewValueName(852, "Tumbleweed"),
		models.NewValueName(853, "Vampire Thorn"),
		models.NewValueName(854, "Cartagra"),
		models.NewValueName(856, "Nautiloid"),
		models.NewValueName(857, "Exocite"),
		models.NewValueName(858, "Anguiform"),
		models.NewValueName(859, "Leap Frog"),
		models.NewValueName(860, "Lizard"),
		models.NewValueName(861, "Litwor Chicken"),
		models.NewValueName(862, "Slagworm"),
		models.NewValueName(863, "Hell's Rider"),
		models.NewValueName(865, "Onion Knight"),
		models.NewValueName(866, "Magitek Armor"),
		models.NewValueName(867, "Sky Armor"),
		models.NewValueName(868, "Satellite"),
		models.NewValueName(869, "Armored Weapon"),
		models.NewValueName(870, "Spritzer"),
		models.NewValueName(871, "Flan"),
		models.NewValueName(872, "Outcast"),
		models.NewValueName(873, "Humpty"),
		models.NewValueName(874, "Brainpan"),
		models.NewValueName(875, "Cruller"),
		models.NewValueName(876, "Cactuar"),
		models.NewValueName(877, "Bandit"),
		models.NewValueName(878, "Harvester"),
		models.NewValueName(879, "Bomb"),
		models.NewValueName(880, "Still Life"),
		models.NewValueName(881, "Lunatys"),
		models.NewValueName(882, "Veil Dancer"),
		models.NewValueName(883, "Hill Gigas"),
		models.NewValueName(884, "Tonberry"),
		models.NewValueName(885, "Magic Urn"),
		models.NewValueName(886, "Mover"),
		models.NewValueName(887, "Figaro Lizard"),
		models.NewValueName(888, "Devoahan"),
		models.NewValueName(889, "Aspiran"),
		models.NewValueName(890, "Ghost"),
		models.NewValueName(891, "Crawler"),
		models.NewValueName(892, "Sand Ray"),
		models.NewValueName(893, "Alacran"),
		models.NewValueName(894, "Actinian"),
		models.NewValueName(895, "Sandhorse"),
		models.NewValueName(896, "Darkside"),
		models.NewValueName(897, "Malboro"),
		models.NewValueName(898, "Urok"),
		models.NewValueName(899, "Foper"),
		models.NewValueName(900, "Guard Leader"),
		models.NewValueName(901, "Corporal"),
		models.NewValueName(902, "General"),
		models.NewValueName(903, "Covert"),
		models.NewValueName(904, "Kamui"),
		models.NewValueName(905, "Warlock"),
		models.NewValueName(906, "Cherry"),
		models.NewValueName(907, "Joker"),
		models.NewValueName(908, "Iron Fist"),
		models.NewValueName(909, "Devil"),
		models.NewValueName(910, "Provoker"),
		models.NewValueName(911, "Cloudwraith"),
		models.NewValueName(912, "Mahadeva"),
		models.NewValueName(913, "Vector Hound"),
		models.NewValueName(914, "Peeper"),
		models.NewValueName(915, "Stunner"),
		models.NewValueName(916, "Sorath"),
		models.NewValueName(917, "Destroyer"),
		models.NewValueName(918, "Chippirabbit"),
		models.NewValueName(919, "Coeurl Cat"),
		models.NewValueName(920, "Bloodfang"),
		models.NewValueName(921, "Hunting Hound"),
		models.NewValueName(922, "Gorgias"),
		models.NewValueName(923, "Don"),
		models.NewValueName(924, "Murussu"),
		models.NewValueName(925, "Wartpuck"),
		models.NewValueName(926, "Gorgimera"),
		models.NewValueName(927, "Behemoth King"),
		models.NewValueName(928, "Vector Lythos"),
		models.NewValueName(929, "Wyvern"),
		models.NewValueName(930, "Zombie Dragon"),
		models.NewValueName(931, "Dragon"),
		models.NewValueName(932, "Primeval Dragon"),
		models.NewValueName(933, "Weredragon"),
		models.NewValueName(934, "Cirpius"),
		models.NewValueName(935, "Sprinter"),
		models.NewValueName(936, "Lenergia"),
		models.NewValueName(937, "Marchosias"),
		models.NewValueName(938, "Gloomwind"),
		models.NewValueName(939, "Dropper"),
		models.NewValueName(940, "Rock Wasp"),
		models.NewValueName(941, "Grasswyrm"),
		models.NewValueName(942, "Luridan"),
		models.NewValueName(943, "Twinscythe"),
		models.NewValueName(944, "Paraladia"),
		models.NewValueName(945, "Exoray"),
		models.NewValueName(946, "Crusher"),
		models.NewValueName(947, "Ouroboros"),
		models.NewValueName(948, "Acrophies"),
		models.NewValueName(949, "Schmidt"),
		models.NewValueName(950, "Devourer"),
		models.NewValueName(951, "Cancer"),
		models.NewValueName(952, "Gigantoad"),
		models.NewValueName(953, "Basilisk"),
		models.NewValueName(954, "Medusa Chicken"),
		models.NewValueName(955, "Landworm"),
		models.NewValueName(956, "Test Rider"),
		models.NewValueName(957, "Pluto Armor"),
		models.NewValueName(958, "Onion Dasher"),
		models.NewValueName(959, "Heavy Armor"),
		models.NewValueName(960, "Chaser"),
		models.NewValueName(961, "Gamma"),
		models.NewValueName(962, "Poplium"),
		models.NewValueName(963, "Intangir"),
		models.NewValueName(964, "Misfit"),
		models.NewValueName(965, "Creature"),
		models.NewValueName(966, "Enuo"),
		models.NewValueName(967, "Deepeye"),
		models.NewValueName(968, "Unseelie"),
		models.NewValueName(969, "Neck Hunter"),
		models.NewValueName(970, "Grenade"),
		models.NewValueName(971, "Alluring Rider"),
		models.NewValueName(972, "Pandora"),
		models.NewValueName(973, "Blade Dancer"),
		models.NewValueName(974, "Gigantos"),
		models.NewValueName(975, "Magna Roader"),
		models.NewValueName(976, "Lycaon"),
		models.NewValueName(977, "Parasite"),
		models.NewValueName(978, "Land Ray"),
		models.NewValueName(979, "Antares"),
		models.NewValueName(980, "Anemone"),
		models.NewValueName(981, "Moonform"),
		models.NewValueName(982, "Specter"),
		models.NewValueName(983, "Great Malboro"),
		models.NewValueName(984, "Bonnacon"),
		models.NewValueName(985, "Oceanus"),
		models.NewValueName(986, "Living Dead"),
		models.NewValueName(988, "Face"),
		models.NewValueName(989, "Outsider"),
		models.NewValueName(990, "Coco"),
		models.NewValueName(991, "Zeveak"),
		models.NewValueName(992, "Nightwalker"),
		models.NewValueName(993, "Demon Knight"),
		models.NewValueName(994, "Imperial Elite"),
		models.NewValueName(995, "Desert Hare"),
		models.NewValueName(996, "Wizard"),
		models.NewValueName(997, "Devil Fist"),
		models.NewValueName(998, "Illuyankas"),
		models.NewValueName(999, "Sergeant"),
		models.NewValueName(1000, "Aspidochelon"),
		models.NewValueName(1001, "Knotty"),
		models.NewValueName(1002, "Luna Wolf"),
		models.NewValueName(1003, "Belzecue"),
		models.NewValueName(1004, "Caladrius"),
		models.NewValueName(1005, "Tzakmaqiel"),
		models.NewValueName(1006, "Lukhavi"),
		models.NewValueName(1007, "Eukaryote"),
		models.NewValueName(1008, "Land Grillon"),
		models.NewValueName(1009, "Goetia"),
		models.NewValueName(1010, "Greater Mantis"),
		models.NewValueName(1011, "Bogy"),
		models.NewValueName(1012, "Purusa"),
		models.NewValueName(1013, "Black Dragon"),
		models.NewValueName(1014, "Adamankary"),
		models.NewValueName(1015, "Dante"),
		models.NewValueName(1016, "Platinum Dragon"),
		models.NewValueName(1017, "Duel Armor"),
		models.NewValueName(1018, "Psychos"),
		models.NewValueName(1019, "Mousse"),
		models.NewValueName(1020, "Shambling Corpse"),
		models.NewValueName(1021, "Punisher"),
		models.NewValueName(1022, "Balloon"),
		models.NewValueName(1023, "Gobbledygook"),
		models.NewValueName(1024, "Great Behemoth"),
		models.NewValueName(1025, "Scorpion"),
		models.NewValueName(1026, "Chaos Dragon"),
		models.NewValueName(1027, "Spitfire"),
		models.NewValueName(1028, "Vector Chimera"),
		models.NewValueName(1029, "Lich"),
		models.NewValueName(1030, "Rukh"),
		models.NewValueName(1031, "Magna Roader"),
		models.NewValueName(1032, "Bug"),
		models.NewValueName(1033, "Seaflower"),
		models.NewValueName(1034, "Fortis"),
		models.NewValueName(1035, "Venobennu"),
		models.NewValueName(1036, "Galypdes"),
		models.NewValueName(1037, "Junk"),
		models.NewValueName(1038, "Mandrake"),
		models.NewValueName(1039, "Valeor"),
		models.NewValueName(1040, "Amduscias"),
		models.NewValueName(1041, "Necromancer"),
		models.NewValueName(1042, "Glasya Labolas"),
		models.NewValueName(1043, "Magna Roader"),
		models.NewValueName(1044, "Wild Rat"),
		models.NewValueName(1045, "Gold Bear"),
		models.NewValueName(1046, "InnoSent"),
		models.NewValueName(1047, "Clymenus"),
		models.NewValueName(1048, "Garm"),
		models.NewValueName(1049, "Daedalus"),
		models.NewValueName(1050, "Baalzephon"),
		models.NewValueName(1051, "Ahriman"),
		models.NewValueName(1052, "Death Machine"),
		models.NewValueName(1053, "Metal Hitman"),
		models.NewValueName(1054, "Io"),
		models.NewValueName(1055, "Skip"),
	}
)
