package consts

import (
	"pixel-remastered-save-editor/models"
)

var (
	Weapons = []models.NameValue{
		models.NewValueName(1, "Empty"),
		models.NewValueName(2, "Dagger"),
		models.NewValueName(3, "Mythril Knife"),
		models.NewValueName(4, "Main Gauche"),
		models.NewValueName(5, "Air Knife"),
		models.NewValueName(6, "Thief's Knife"),
		models.NewValueName(7, "Assassin's Dagger"),
		models.NewValueName(8, "Man-Eater"),
		models.NewValueName(9, "Swordbreaker"),
		models.NewValueName(10, "Gladius"),
		models.NewValueName(11, "Valiant Knife"),
		models.NewValueName(12, "Mythril Sword"),
		models.NewValueName(13, "Great Sword"),
		models.NewValueName(14, "Rune Blade"),
		models.NewValueName(15, "Flametongue"),
		models.NewValueName(16, "Icebrand"),
		models.NewValueName(17, "Thunder Blade"),
		models.NewValueName(18, "Bastard Sword"),
		models.NewValueName(19, "Stoneblade"),
		models.NewValueName(20, "Blood Sword"),
		models.NewValueName(21, "Enhancer"),
		models.NewValueName(22, "Crystal Sword"),
		models.NewValueName(23, "Falchion"),
		models.NewValueName(24, "Soul Saber"),
		models.NewValueName(25, "Organyx"),
		models.NewValueName(26, "Excalibur"),
		models.NewValueName(27, "Zantetsuken"),
		models.NewValueName(28, "Lightbringer"),
		models.NewValueName(29, "Ragnarok"),
		models.NewValueName(30, "Ultima Weapon"),
		models.NewValueName(31, "Mythril Spear"),
		models.NewValueName(32, "Trident"),
		models.NewValueName(33, "Heavy Lance"),
		models.NewValueName(34, "Partisan"),
		models.NewValueName(35, "Holy Lance"),
		models.NewValueName(36, "Golden Spear"),
		models.NewValueName(37, "Radiant Lance"),
		models.NewValueName(38, "Impartisan"),
		models.NewValueName(39, "Kunai"),
		models.NewValueName(40, "Kodachi"),
		models.NewValueName(41, "Sakura"),
		models.NewValueName(42, "Sasuke"),
		models.NewValueName(43, "Ichigeki"),
		models.NewValueName(44, "Kagenui"),
		models.NewValueName(45, "Ashura"),
		models.NewValueName(46, "Kotetsu"),
		models.NewValueName(47, "Kikuichimonji"),
		models.NewValueName(48, "Kazekiri"),
		models.NewValueName(49, "Murasame"),
		models.NewValueName(50, "Masamune"),
		models.NewValueName(51, "Murakumo"),
		models.NewValueName(52, "Mutsunokami"),
		models.NewValueName(53, "Healing Rod"),
		models.NewValueName(54, "Mythril Rod"),
		models.NewValueName(55, "Flame Rod"),
		models.NewValueName(56, "Ice Rod"),
		models.NewValueName(57, "Thunder Rod"),
		models.NewValueName(58, "Poison Rod"),
		models.NewValueName(59, "Holy Rod"),
		models.NewValueName(60, "Gravity Rod"),
		models.NewValueName(61, "Punisher"),
		models.NewValueName(62, "Magus Rod"),
		models.NewValueName(63, "Chocobo Brush"),
		models.NewValueName(64, "Da Vinci Brush"),
		models.NewValueName(65, "Magical Brush"),
		models.NewValueName(66, "Rainbow Brush"),
		models.NewValueName(67, "Shuriken"),
		models.NewValueName(68, "Fuma Shuriken"),
		models.NewValueName(69, "Pinwheel"),
		models.NewValueName(70, "Chain Flail"),
		models.NewValueName(71, "Moonring Blade"),
		models.NewValueName(72, "Morning Star"),
		models.NewValueName(73, "Boomerang"),
		models.NewValueName(74, "Rising Sun"),
		models.NewValueName(75, "Hawkeye"),
		models.NewValueName(76, "Bone Club"),
		models.NewValueName(77, "Sniper"),
		models.NewValueName(78, "Wing Edge"),
		models.NewValueName(79, "Cards"),
		models.NewValueName(80, "Darts"),
		models.NewValueName(81, "Death Tarot"),
		models.NewValueName(82, "Viper Darts"),
		models.NewValueName(83, "Dice"),
		models.NewValueName(84, "Fixed Dice"),
		models.NewValueName(85, "Metal Knuckles"),
		models.NewValueName(86, "Mythril Claws"),
		models.NewValueName(87, "Kaiser Knuckles"),
		models.NewValueName(88, "Venom Claws"),
		models.NewValueName(89, "Burning Fist"),
		models.NewValueName(90, "Dragon Claws"),
		models.NewValueName(91, "Tigerfang"),
	}
)
