# workflow name
name: Generate Release Artifacts

# on events
on:
  release:
    types:
      - created

# workflow tasks
jobs:
  xgo:
    strategy:
      fail-fast: false
      matrix:
        go_version:
          - 1.16
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build with xgo
        uses: crazy-max/ghaction-xgo@v1
        with:
          xgo_version: latest
          go_version: ${{ matrix.go_version }}
          dest: build
          prefix: final-fantasy-vi-save-editor
          targets: windows/386,windows/amd64,linux/386,linux/amd64,darwin/386,darwin/amd64
          v: true
          x: false
          race: false
          ldflags: -s -w
          buildmode: default
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: ./build/*
