# workflow name
name: Generate Release Artifacts

# on events
on:
  release:
    types:
      - created
      - edited

# workflow tasks
jobs:
  generate:
    name: Generate cross-platform builds
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Generate build files
        uses: thatisuday/go-cross-build@v1
        with:
          platforms: 'linux/amd64, darwin/amd64, windows/amd64'
          name: 'final-fantasy-vi-save-editor'
          compress: 'true'
          dest: 'dist'
